### ISSUE TITLE
TestCase analyser doesn't handle nullables

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit.analyzers#1]
The TestCase analyser incorrectly flags up the below test, with nullable parameters. 

![image](https://cloud.githubusercontent.com/assets/4837132/20669564/ccd6b484-b56c-11e6-9110-bb2aa3b16409.png)

![image](https://cloud.githubusercontent.com/assets/4837132/20669569/d62f762e-b56c-11e6-8fd7-217780d48410.png)

I had a quick test with optional parameters and params, and they both look good!

**Comment by JasonBock** [comment]
Should be able to fix this pretty easy.

**Comment by JasonBock** [comment]
@ChrisMaddock get latest and see if it's fixed now. If so, please close the issue.

**Comment by ChrisMaddock** [comment]
Yep, thanks!
