### ISSUE TITLE
Is this package on NuGet?

### ISSUE THREAD

**Issue by 304NotModified** [nunit/nunit.analyzers#10]
I can't find it

**Comment by rprouse** [comment]
This project hasn't been released yet and progress has stalled a bit.

**Comment by SamJongenelen** [comment]
I would love to have these w/o having to build it (like xUnit does) 

Might it be stable enough for a nuget pre release version?

**Comment by jnm2** [comment]
I wish I could reference `NUnit` and have the analyzers on by default unless turned off, but that would require bundling the build output of this repository in the `NUnit` package under `/analyzers` or else adding a package dependency on a package published by this repo. I really like the paradigm where the analyzers come out of the box with the API.

**Comment by mikkelbu** [comment]
@SamJongenelen I don't think that the analyzers are stable enough. I just tried to compile them and opening some different files, and I got several NREs thrown.

**Comment by CharliePoole** [comment]
Hmm... We accepted this project provisionally as experimental. But can a user see that status anywhere?

**Comment by JohanLarsson** [comment]
I wrote a couple of analyzers for NUnit in [this](https://www.nuget.org/packages/Gu.Analyzers/) nuget. Took  
 about an hour, you can use them until this package is released.

**Comment by mikkelbu** [comment]
And now the nuget package can be found on MyGet, https://www.myget.org/feed/nunit-analyzers/package/nuget/NUnit.Analyzers.
