### ISSUE TITLE
Detect scenarios where expected and actual are switched

### ISSUE THREAD

**Issue by jnm2** [nunit/nunit.analyzers#113]
For example, if the `actual` argument to `Assert.AreEqual` is constant?

https://github.com/nunit/nunit/pull/3172#discussion_r261806723

**Comment by mikkelbu** [comment]
This could be done together with - or as part of - #40.

**Comment by jnm2** [comment]
Oh, #40 is what I was trying to find! This sounded familiar. Okay for me to close as covered by #40?

**Comment by mikkelbu** [comment]
Closed as a duplicate of #40.
