### ISSUE TITLE
Cannot create Analyzer classes in Visual Studio 2019 RC 3

### ISSUE THREAD

**Issue by rprouse** [nunit/nunit.analyzers#119]
Loading the latest version of the Analyzers shows the following errors in Visual Studio 2019 RC 3

```
Warning	CS8032 An instance of analyzer NUnit.Analyzers.TestCaseSourceUsage.TestCaseSourceUsesStringAnalyzer cannot be created from C:\Users\rob\.nuget\packages\nunit.analyzers\0.1.0-dev-00134\analyzers\dotnet\cs\nunit.analyzers.dll: Could not load type 'NUnit.Analyzers.TestCaseSourceUsage.TestCaseSourceUsesStringAnalyzer' from assembly 'nunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..

Warning	CS8032 An instance of analyzer NUnit.Analyzers.ConstActualValueUsage.ConstActualValueUsageAnalyzer cannot be created from C:\Users\rob\.nuget\packages\nunit.analyzers\0.1.0-dev-00134\analyzers\dotnet\cs\nunit.analyzers.dll: Could not load type 'NUnit.Analyzers.ConstActualValueUsage.ConstActualValueUsageAnalyzer' from assembly 'nunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..

Warning	CS8032 An instance of analyzer NUnit.Analyzers.ParallelizableUsage.ParallelizableUsageAnalyzer cannot be created from C:\Users\rob\.nuget\packages\nunit.analyzers\0.1.0-dev-00134\analyzers\dotnet\cs\nunit.analyzers.dll: Could not load type 'NUnit.Analyzers.ParallelizableUsage.ParallelizableUsageAnalyzer' from assembly 'nunit.analyzers, Version=0.1.0.0, Culture=neutral, PublicKeyToken=null'..
```

Is the third one causing #118?

**Comment by mikkelbu** [comment]
I've not yet tried VS 2019, but the issue sounds related to dotnet/roslyn#32226, but that should be corrected now (can you see if it is the same problem using [fuslogvw](https://docs.microsoft.com/en-us/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer)?). Similar problem also occurred in DotNetAnalyzers/StyleCopAnalyzers#2633, but that could be corrected by upgrading the client code.

I'll see if I have time to install VS 2019 this week.

Charlie also ran into CS8032, but with a different message. When building via cake he got
```
CSC : error CS8032: An instance of analyzer NUnit.Analyzers.ClassicModelAssertUsage.ClassicModelAssertUsageAnalyzer cannot be created from REMOVED\.nuget\packages\nunit.analyzers\0.1.0-dev-00079\analyzers\dotnet\cs\nunit.analyzers.dll : Exception has been thrown by the target of an invocation.. [REMOVED\dev\NUnit\nunit-console\src\NUnitEngine\nunit.engine.tests\nunit.engine.tests.csproj]
CSC : error CS8032: An instance of analyzer NUnit.Analyzers.ClassicModelAssertUsage.ClassicModelAssertUsageAnalyzer cannot be created from REMOVED\.nuget\packages\nunit.analyzers\0.1.0-dev-00079\analyzers\dotnet\cs\nunit.analyzers.dll : Exception has been thrown by the target of an invocation.. [REMOVED\dev\NUnit\nunit-console\src\NUnitEngine\nunit.engine.tests\nunit.engine.tests.csproj]
CSC : error CS8032: An instance of analyzer NUnit.Analyzers.ClassicModelAssertUsage.ClassicModelAssertUsageAnalyzer cannot be created from REMOVED\.nuget\packages\nunit.analyzers\0.1.0-dev-00079\analyzers\dotnet\cs\nunit.analyzers.dll : Exception has been thrown by the target of an invocation.. [REMOVED\dev\NUnit\nunit-console\src\NUnitEngine\nunit.engine.tests\nunit.engine.tests.csproj]
An error occurred when executing task 'Build'.
```
And when building in the IDE there was warning messages like 
```
AD0001    Analyzer 'NUnit.Analyzers.TestCaseUsage.TestMethodUsageAnalyzer' threw an exception of type 'System.IO.FileNotFoundException' with message 'Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral,
```

**Comment by mikkelbu** [comment]
@rprouse Exactly how and when are you getting these warnings? I downloaded the newest VS (Visual Studio 2019 RC.3), cloned https://github.com/rprouse/NUnitDemo, and added the analyzers using `Install-Package NUnit.Analyzers -Version 0.1.0-dev-00134 -Source https://www.myget.org/F/nunit-analyzers/api/v3/index.json`, but I don't get any warnings when building.

**Comment by rprouse** [comment]
Hmm, maybe we can close this. I ran into the problem in the NUnitDemo project that you tried. I went in and re-enabled the analyzers and no longer see the problem. It originally happened using the NuGet UI in Visual Studio. I added the package and the errors appeared. It didn't require a build.

I've tested again by uncommenting the package reference in the project file and by adding the package using the UI, but I no longer see the error.

I am going to close this as a transient error. Feel free to reopen if you feel it needs to be looked at.

**Comment by mikkelbu** [comment]
The closest I came to reproducing the problem was when I by accident was using 2 versions of the analyzer in the same project. One version came from NuGet and the other from vsix (as I was debugging the analyzer and by acciendent opened a project that also

**Comment by ssg** [comment]
This happened to me too with NUnit.Analyzers 3.1.0. (It has never happened with previous versions)

**Comment by mikkelbu** [comment]
@ssg I guess this was not in VS 2019 RC 3 as in this issue?

Usually, these kinds of errors occur when one update between versions as VS (sometimes) keep references to the old version in caches etc. Does it solve the problem if you clean up all the build output from VS (e.g. remove `.vs`, `bin`, `obj` folders) and then restore the nuget package. If you use git then e.g. a `git clean -xdf` to remove all that is not checked into git.

**Comment by ssg** [comment]
No, this is VS 16.9.4, and you were right; cleaning `.vs/` folder fixed the issue, thanks!
