### ISSUE TITLE
Add analyzer to capture missing properties

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#128]
Given we have a test like below, were `fixtures` has the static type `IEnumerable<TestSuite>`
```csharp
        [Test]
        public void AbstractClassNotAllowed()
        {
            var abstractType = typeof(AbstractSetupClass);
            var fixtures = new SetUpFixtureAttribute().BuildFrom(new TypeWrapper(abstractType));
            Assert.That(fixtures, Has.Count.EqualTo(0));
...
```
Then test fails run-time with
```
Error : NUnit.Framework.Attributes.SetUpFixtureAttributeTests.StaticClassIsAllowed
System.ArgumentException : Property Count was not found on NUnit.Framework.Internal.TestSuite[].
Parameter name: name
   at NUnit.Framework.Constraints.PropertyConstraint.ApplyTo[TActual](TActual actual)
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
```
It would be nice to capture this beforehand using an analyzer.

Later we can also use this for the general setting with the constraint `Has.Property("someproperty")`.

**Comment by Dreamescaper** [comment]
Do we have to account for properties, unknown at compile time?
Or simply expect user to disable analyzer, if such occurs (I expect it won't be very often)?

**Comment by mikkelbu** [comment]
I think we should just account for the compile-time properties.

**Comment by Dreamescaper** [comment]
I'll take that, if you don't mind.

**Comment by mikkelbu** [comment]
I don't mind it at all 😄. I'll probably have time to review it this weekend (hopefully Friday)
