### ISSUE TITLE
"Sequence contains no elements" in ClassicModelAssertUsageAnalyzer.AnalyzeInvocation

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#13]
The code has the assumption that every `InvocationExpression` is inside a `MethodDeclarationSyntax`. This is not the case for nunit.nunit\src\NUnitFramework\tests\Api\FrameworkControllerTests.cs that has invocations as part of of a field assignment
```
public class FrameworkControllerTests
{
...
    private static readonly string MOCK_ASSEMBLY_NAME = typeof(MockAssembly).GetTypeInfo().Assembly.FullName;
...
}
```
So the code fails with an `System.InvalidOperationException` - "Sequence contains no elements" - in 
```
if(!context.Node.Ancestors().OfType<MethodDeclarationSyntax>().Single().ContainsDiagnostics)
```

**Comment by jnm2** [comment]
I have a feeling that any time an analyzer uses `Single`, `SingleOrDefault` or `FirstOrDefault`, or misses a null check, it's probably being naive. 😃
