### ISSUE TITLE
Bump versions of nunit, nunit-console, and NUnit3TestAdapter

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#131]
When the new version of nunit is release - release 3.12 - then we should bump the versions of all the nunit packages we use.

Changes in cake-script (consolerunner) and in project files.

**Comment by Dreamescaper** [comment]
Can we use '*' nuget reference wildcard in project files?
To use latest stable version automatically?

**Comment by mikkelbu** [comment]
I don't know whether it works in project files, but my initial thought is also that I prefer to keep things like this fixed and explicit, but I'm ready to be convinced otherwise :)

**Comment by Dreamescaper** [comment]
Nope, just a thought.
Manual update every half a year shouldn't be an issue :)
