### ISSUE TITLE
Constraint analyzers have a lot of repeating code

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit.analyzers#134]
Constraints analyzers (classic assert analyzers, IgnoreCaseUsage, ConstActaulValue etc) have a lot of similar code (check if assert, get actual/expected arguments etc).

Probably makes sense to
a) Create some `AssertExpressionHelper` with commonly used methods
b) Create abstract class `AssertionAnalyzer` with existing check for assert.

**Comment by mikkelbu** [comment]
I agree. 

Currently, my overall "plan" was the following:
* Define formats, categories of analyzers, #84 
* Document them or at least set up the skeleton, #96 
* Create the 2.0 release (release notes, packaging, release branch, nuget upload, tags ...)
* Clean up the code (reduce nesting, remove duplication, extract helper methods)

But this is mostly as I want to release in the near future :)
