### ISSUE TITLE
Pre-release nuget packages should be created with unique assembly versions

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit.analyzers#135]
Probably build number should be used in assembly version. Otherwise - after package upgrade VS has to be restarted. Otherwise warnings 'An instance of analyzer ClassName cannot be created' are present.

Similar issue:
https://github.com/microsoft/vs-threading/issues/279

**Comment by mikkelbu** [comment]
I wonder if this will also solve the problem in #120?

**Comment by Dreamescaper** [comment]
Not sure.
Warnings I saw were something like this:  
`Could not load type 'Fully.Qualified.Analyzer' from assembly 'nunit.analyzers'`

Nothing about `System.Runtime`.
