### ISSUE TITLE
Make analyzers suggesting refactoring to the constraint model default disabled?

### ISSUE THREAD

**Issue by JohanLarsson** [nunit/nunit.analyzers#145]
For example `NUnit2001` warns on `Assert.False(expression)` and offers refactoring to `Assert.That(expression, Is.False)`.

From what I understand this is mostly a style choice and while opinionated analyzers are nice for consistency it may be poor ergonomics to push users away from their preferred API.

Downside to making it default disabled is that it will not be easily discoverable. Upside is that it makes the style choice configurable and opt-in.

We can perhaps use the GitHub API to query for usage statistics on the different APIs?

**Comment by Dreamescaper** [comment]
I agree.
Unless we want to deprecate classic assertion model, it shouldn't be warning. 
I wouldn't disable it by default either. I would suggest making it Info.

**Comment by mikkelbu** [comment]
There was a lot of discussion about the severity of the "ClassicModelAssertUsage" analyzers in #9 (search for Info in the comments), but I did not give it much thought when I took over the project (also, I am probably biased as I was advocating the constraint based model at my old job), so I just left the analyzers as a warning.

I agree with @Dreamescaper and think to begin with we should change the severity to Info and leave the analyzer enabled. This still makes it easy to use the fixer and the effect on the IDE is not too intrusive (just 3 dots). If/when we get more feedback then we can consider this choice.

Ps. We should also change the documentation of the analyzers as commented in https://github.com/nunit/nunit.analyzers/pull/144#discussion_r296458983.

Regarding querying the GitHub API for usage statistics then I think that it could be interesting, but I'm quite sure that this will be too large a task for me in any near future 😄.

**Comment by OsirisTerje** [comment]
I am not sure I agree on this.
The default model is the constraint model, using the classic model means you add another layer.  
For the simple example above, I agree it doesnt matter much, but when you look at Assert.AreEqual syntax, the constraint model is less prone to user errors.  
IMHO I believe we *should* give out recommendations.   From courses and workshops I have run on this, many devs don't even know about the constraint model.  The analyzer then points them in the right direction, and the majority (in my experience) prefers it. 
 If a user disagree, it is easy to reconfigure anyway.

**Comment by pantosha** [comment]
Any news? 
It seems that this bug is only one stopper for the first version releasing. It will be very helpful to resolve it and publish the first version at nuget.com.

**Comment by mikkelbu** [comment]
@pantosha I hope to have something ready within a couple of weeks (my schedule is quite busy at the moment), so until then you can use the myget feed.

**Comment by pantosha** [comment]
Great! @mikkelbu , thanks for the answer.
