### ISSUE TITLE
Analyzer for non-test methods to be non-public

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit.analyzers#147]
In our team we have a convention that only test methods can be public in test classes. If any helper methods are present for some reason, they should be private. Would be great to have an analyzer for that.

Probably should be disabled by default though.

**Comment by mikkelbu** [comment]
Sounds reasonable.

We should probably include information of whether an analyzer is enabled by default or not both in the documentation of the analyzer and in the index https://github.com/nunit/nunit.analyzers/blob/master/documentation/index.md.

**Comment by manfred-brands** [comment]
As we have the same rule, I will add a rule for this.

**Comment by manfred-brands** [comment]
Created PR #265 

I do allow for `protected` methods as we have base classes defining `protected virtual` methods.
CS6028 already fires for adding a `protected` method in a `sealed` class so I didn't test for that here.

**Comment by mikkelbu** [comment]
Resolved by #265
