### ISSUE TITLE
Analyzer update needed for string->datetime offset conversion in testcaseattribute

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit.analyzers#148]
NUnit Version: 3.13

Support was added for string->datetime offset conversion in https://github.com/nunit/nunit/issues/3053

But I've noticed I'm getting an analyzer info message about an invalid conversion when using it. We should update the analyzers to be aware of the new type conversion.

Assuming we want to go ahead with this change, I'd actually be happy to try to implement too. Would be a much-wanted introduction for me to Roslyn analyzers.

**Comment by mikkelbu** [comment]
Hi @stevenaw. I think the addition sounds like a good idea, and you are most welcome to work on it. Please write if you run into problems.

**Comment by stevenaw** [comment]
Thanks @mikkelbu 
I got a little busy with some things, but I think this went surprisingly smoothly.
