### ISSUE TITLE
Analyzer doesn't allow me to pass string[] as first parameter.

### ISSUE THREAD

**Issue by Deni35** [nunit/nunit.analyzers#155]
Unfortunately passing `string[]` as first parameter leads to a problems. 

Compiler is choosing `TestCaseAttribute(params object[] arguments)` constructor and it leads to error: _An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type_. If I understand right, then casting `string[]` to `object[]` is not working for attribute's parameters.

We must cast array to `object`  that compiler to choose correct constructor.

But in this case analyzer produces error: _Error NUnit1001 The value of the argument at position '0' cannot be assigned to the argument 'values'_.  

        [TestCase( (object) new[] { "text" } )]
        public void Test_02(string[] values) {
        }

May be there are another ways to pass `string[]` at first position?

**Comment by mikkelbu** [comment]
@Deni35 Another way to "force " compiler to use the correct constructor is to use a named argument in the constructor. The following should also work (and avoid the cast to `object`) 
```csharp
        [TestCase(arg: new[] { "text" })]
```

**Comment by mikkelbu** [comment]
@Deni35 I'm closing this is one can use the workaround instead of casting the argument. We could in theory also handle casted values (or just ignore them) in the analyzers, but I think that this would provide very little value compared to the effort, so for now I don't think we should spent time on this.
