### ISSUE TITLE
Make the extension work with VS 2017

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#16]
Probably by following the description in https://docs.microsoft.com/en-us/visualstudio/extensibility/how-to-roundtrip-vsixs

Remember to update documentation about building

**Comment by CharliePoole** [comment]
Have you considered going the nuget-only route?

**Comment by jnm2** [comment]
@mikkelbu I found the built-in NuGet + VSIX analyzer template quite finicky and followed the guide for setting up my own from scratch to get away from packages.config. (https://roslyn-analyzers.readthedocs.io/en/latest/how-to-start.html#the-pro-way) It provides the flexibility I've come to demand from the new csproj format. If this sounds interesting, here's what it looks like in one of my analyzer projects:

https://github.com/jnm2/SourceHeaderAnalyzer/blob/22093218482b68c5c4e68b1b244833a175c06ba3/src/SourceHeaderAnalyzer/SourceHeaderAnalyzer.csproj

VSIX project (only for F5 debug): https://github.com/jnm2/SourceHeaderAnalyzer/tree/22093218482b68c5c4e68b1b244833a175c06ba3/src/SourceHeaderAnalyzer.Debug

**Comment by jnm2** [comment]
Oh wait, that's not the best example because I haven't packed it yet. Comparing one of the analyzer projects at work, this is what the analyzer csproj would like like when ready for use with `/t:Pack`:

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard1.4</TargetFramework>

    <Version>1.0.0</Version>
    <Authors>jnm2</Authors>
    <Copyright>Copyright © 2018 Joseph Musser</Copyright>
    <AssemblyTitle>Foo code analyzers</AssemblyTitle>
    <Description>$(AssemblyTitle)</Description>
    <PackageTags>Foo analyzer</PackageTags>
    <DevelopmentDependency>True</DevelopmentDependency>
    <BuildOutputTargetFolder>analyzers\dotnet</BuildOutputTargetFolder>

    <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="2.3.2" />
  </ItemGroup>

</Project>
```

**Comment by ChrisMaddock** [comment]
@mikkelbu - this may be interesting for your decision:

https://github.com/wachulski/nunit-migrator/issues/19
