### ISSUE TITLE
Bug: Assert.AreEqual to Assert.That(Is.EqualTo()) doesn't consider types

### ISSUE THREAD

**Issue by jcurl** [nunit/nunit.analyzers#164]
Version NUnit.Analyzers-0.1.0-dev-00205
Using NUnit 2.6.7, within Visual Studio 2019. 

After converting from:

`int value=49; Assert.AreEqual('1', value);`
to 
`int value=49; Assert.That(value, Is.EqualTo('1'));`

will change a passing test case to a failing test case. The conversion should take the types into account so that after the conversion there is a typecast as in the original Assert.AreEqual.

`int value=49; Assert.That(value, Is.EqualTo((int)'1'));`

That's because Assert.AreEqual uses implicit type conversion, where Is.EqualTo() doesn't.

**Comment by mikkelbu** [comment]
This is only a problem in NUnit 2.X, as both assertions pass in NUnit 3. I'm not much for introducing special handling and complexity in the analyzers to handle behaviour in NUnit 2, so I'm leaning towards closing this issue (with the current label), and then if I at some point get more time - and is more finished with the NUnit 3 features - then I can come back to this. But currently, I don't think it realistic in any close future.

Another possibility is to open an issue at https://github.com/nunit-legacy/nunitv2/issues about `int value=49; Assert.That(value, Is.EqualTo('1'));` failing and then see if this can be correct in NUnit 2. I don't know much about the differences between 2 and 3 in the codebase, so I don't have any idea if this is easy to fix. @CharliePoole will probably have a good idea.

**Comment by jcurl** [comment]
Thanks for the confirmation.
