### ISSUE TITLE
Make it possible to run tests both in .NET framework and .NET Core

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#191]
To capture issues like #186 we need to run tests both in a .NET framework setting and in a .NET Core setting.

**Comment by Dreamescaper** [comment]
Simply adding target framework didn't help to reproduce that issue - I've tried :) .
I suppose that's because we create our roslyn project not with design-time assemblies, but with forwarded ones, therefore analyzer is able to find Uri class.

**Comment by manfred-brands** [comment]
We can dual target the nunit.analyzers.tests project by using plural TargetFrameworks:
`<TargetFrameworks>net461;netcoreapp2.1</TargetFrameworks>`

This causes 2 test failures on `AnalyzeWhenTestMethodHasValueTaskReturnTypeAndExpectedResult` and `AnalyzeWhenTestMethodHasValueTaskReturnTypeAndExpectedResultIsIncorrect`.
We can add ValueTask support to .net461 by adding:
`<PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.4" Condition="'$(TargetFramework)' == 'net461'" />`

However the tests still fail with roslyn saying the `methodSymbol.ReturnType` is an `ErrorType`.

Unless one of you knows how to add support to the analyzer itself for ValueTask, I suggest to make these test conditional using `#if !NET461` as ValueTasks were not part of .net framework 4.6 anyhow.

I added a PR (#263) for this.

**Comment by mikkelbu** [comment]
Closed by #263
