### ISSUE TITLE
Handle custom type converters

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#197]
We should be able to handle custom type converters. 

Suggestions from Gitter: https://gitter.im/GuOrg/Gu.Roslyn.Asserts?at=5e7935aa2e334e1b7aefffa0
> One heuristic you could use is to assume that the presence of a type converter for a type means that the type converter can convert from string. That is not a guarantee but it's such a mainline scenario.
...
So that would be a search in the custom attributes on the `targetType` ITypeSymbol
For a custom attribute with whatever the full type name of TypeConverterAttribute is
And that's when `argumentType` is System.String

**Comment by jnm2** [comment]
##### (moved from accidental duplicate https://github.com/nunit/nunit.analyzers/issues/232)

A warning should not be produced. The analyzer can see that CustomType has `[TypeConverter(typeof(CustomTypeConverter))]` even though it can't run it. It's a safe assumption that type converters can convert from `string`. Even without that assumption (say, with an `int` test parameter), the warning message is making a claim that it can't prove.

```cs
using System;
using System.ComponentModel;
using System.Globalization;
using NUnit.Framework;

class C
{
    // NUnit1001 The value of the argument at position '0' of type string cannot be assigned to
    // the argument 'customType' of type CustomType.
    //        ↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓
    [TestCase("String representation")]
    public void M(CustomType customType)
    {
    }
}

[TypeConverter(typeof(CustomTypeConverter))]
struct CustomType
{
    public CustomType(string value)
    {
        Value = value;
    }

    public string Value { get; }

    private sealed class CustomTypeConverter : TypeConverter
    {
        public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
        {
            return sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);
        }

        public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
        {
            return value is string str
                ? new CustomType(str)
                : base.ConvertFrom(context, culture, value);
        }

        public override bool CanConvertTo(ITypeDescriptorContext context, Type destinationType)
        {
            return destinationType == typeof(string) || base.CanConvertTo(context, destinationType);
        }

        public override object ConvertTo(ITypeDescriptorContext context, CultureInfo culture, object value, Type destinationType)
        {
            return destinationType == typeof(string)
                ? value.ToString()
                : base.ConvertTo(context, culture, value, destinationType);
        }
    }
}
```

**Comment by jnm2** [comment]
@mikkelbu Can I contribute this one if no one is working on it?

**Comment by mikkelbu** [comment]
Sure Joseph, you are most welcome to solve this issue. I'll assign it to you.
