### ISSUE TITLE
TestCase analyser interprets number types differently to framework

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit.analyzers#2]
![image](https://cloud.githubusercontent.com/assets/4837132/20670390/9952953e-b570-11e6-9b71-e0abbadedb12.png)

The analyser incorrectly flags the above TestCase's as not being doubles, which NUnit is happy to parse.

With this and #1, I wonder if this is entering something of a rabbit hole. Maybe we should revisit exposing and sharing this functionality from the framework - although from what you said before @JasonBock, that may be technically impossible? What do you think? 😄

**Comment by ChrisMaddock** [comment]
I had a quick dig. Looks like the code at the line below is the source - I don't know how consistent that is across different attributes, if this was to later be expanded!

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TestCaseAttribute.cs#L363

**Comment by JasonBock** [comment]
My implementation does a direct "can I pass in a value of this type to the parameter which has this type?" Looks like NUnit does some conversions if it can, and yes, that code would have to be shared for the analyzer to work the exact same way. But it seems like it's `private`, so I can't call it. Personally, I don't like that if you give an int value to a double that NUnit will try to convert it. I think you should be explicit. If you need to test a conversion, do it within the test.

**Comment by ChrisMaddock** [comment]
Yup - I think this would be definite grounds to expose this and `GetParametersForTestCase(IMethodInfo method)` too. @nunit/core-team?

No comments on good practice - but I imagine changing that now would be a pretty substantial breaking change!

**Comment by ChrisMaddock** [comment]
Just to add - there was an ongoing discussion on how to sync up this sort of logic between all the various different attributes which use it, or something similar. We should probably deal with that at the same time as exposing this, if we go down that route!

**Comment by CharliePoole** [comment]
TestCase attribute has additional conversions to other days sources to compensate for the limitations imposed on Attribute arguments by C#. I can give specific rules if it would help.

This sounds like another good reason to put the analyzers in the framework repo.

**Comment by JasonBock** [comment]
@ChrisMaddock @CharliePoole just to reiterate, I probably won't be able to reuse the logic in the framework because the Compiler API object model doesn't deal with Reflection-based types. I'm guessing I'd have to redo the logic in the analyzer.

**Comment by CharliePoole** [comment]
Not sure what you mean by "Reflection-based" types. Let's take an example: Because decimal can't be used as an argument to an Attribute, TestCaseAttribute will translate a string to a decimal if that's the type required by the test method. Neither Decimal nor String are peculiar to reflection, even though we discover them through reflection.

So, if you wanted to allow for this in your checks, you would need to determine that there is a string corresponding to a decimal argument. IMO, you could leave it there and simply not flag a problem. If you wanted to do more you could check the constant string value to see if it converts to a decimal, but I think that would be going too far. It's enough that you don't flag an error.

Have I misunderstood the issue?

**Comment by CharliePoole** [comment]
NUnit has historically treated all numeric types as convertible in assertions. For example, 5 is equal to 5.0d. This goes back to around 2000.

For test case parameters, we try to generally allow any conversion that C# would do implicitly, but add some extras to make up for limitations in C# WRT attribute arguments. This is more recent - probably only goes back 10 years or so. :-)

IOW, it's not something we can easily change overall, although we can make a few adjustments if necessary. In fact, we have requests to do __more__ conversions rather than less.

**Comment by JasonBock** [comment]
@CharliePoole I mean that if we try to share code that does any type or Reflection-based work, I probably can't use it directly from the analyzer as you just don't get that kind of information in the Compiler API.

What I'd really be looking for is, what types can be converted to what type? E.g. if you give an int in `[TestCase]`,, what method parameter types are acceptable for that given type?

**Comment by CharliePoole** [comment]
I wasn't thinking of sharing code, just info about what conversions are supported. I'll have some time later today to get you better info.

**Comment by ChrisMaddock** [comment]
@JasonBock - did you fix this too, or is something odd going on? The error no longer shows on my new build of master

**Comment by JasonBock** [comment]
@ChrisMaddock Um....no....I'm still seeing the original behavior I wrote, which is to say, if you're expecting a `double` and you give an `int`, you'll get an error.

**Comment by ChrisMaddock** [comment]
Odd - that exact test is no longer showing the error. Maybe there's some cache weirdness going on...

**Comment by JasonBock** [comment]
@ChrisMaddock Could you include a screen shot? Also, look at the error list with warnings, maybe something is failing that I didn't anticipate.

**Comment by JasonBock** [comment]
@ChrisMaddock Dug a bit deeper into the source code, and it seems like `PerformSpecialConversion` is what I need to look at:

https://github.com/nunit/nunit/blob/master/src/NUnitFramework/framework/Attributes/TestCaseAttribute.cs#L363

Though I have to be careful here in that if `Convert.ChangeType` fails, I have to catch the exceptions for each argument so I can get information for each argument. Also, the NUnit code seems to allow a `null` to be passed to a value type, which isn't allowed in C#. But I may be reading the code wrong too...

**Comment by JasonBock** [comment]
I think I got the code done for mimicking what NUnit does at runtime. Need to get tests around it :)

**Comment by ChrisMaddock** [comment]
Sounds good @JasonBock! Sorry I haven't got back to these issues...been a busy week. Will try and do so sometime soon. 😄

**Comment by JasonBock** [comment]
I just updated the code so that I think it follows what NUnit does at runtime. @ChrisMaddock or anyone else, if you could give this a try, let me know if I've missed any cases or the implementation is whacked - thanks!

**Comment by ChrisMaddock** [comment]
Sorry @JasonBock, did mean to get back to these! Busy weekend, but will try and take a look next week.

**Comment by ChrisMaddock** [comment]
@JasonBock - can you run me through how you test these?

Before I was trying with existing libraries, but getting a number of errors, although they could have been due to mismatched framework versions. So instead, I thought I'd use your 'playground' in the solution - although when I add the analyzers to that project, I get the below errors. 

Any ideas what I'm missing? This is VS 2015.

![image](https://cloud.githubusercontent.com/assets/4837132/21313941/5ef00232-c5ec-11e6-9d7f-289276db0c51.png)

**Comment by JasonBock** [comment]
@ChrisMaddock I really don't know why you're getting those errors. I basically do two things to test the analyzers:

* I write unit tests
* I run the VSIX project, which launches another version of VS with the analyzers installed as an extension

I've tried installing the analyzers from the NuGet file from another project and that does work locally with no issues, so....I'm not sure what to tell you. :(

**Comment by ChrisMaddock** [comment]
@JasonBock - I was adding a reference to the nunit.analyzer.dll. Using a debug instance sounds much more reliable - I'll test with that - deployment will hopefully 'just work' when we get to it! 😄

**Comment by JasonBock** [comment]
@ChrisMaddock  OHHHH.....huh, I have never done that :). Typically I get analyzers either a NuGet package (which will install the analyzers correctly) or as a VSIX. Note that you don't have to do a "debug" build to do this - it can be "release" :).

**Comment by ChrisMaddock** [comment]
Sorry @JasonBock - I've been rubbish with these issues. This looks to be fixed - nice one. 😄
