### ISSUE TITLE
Document all the analyzers

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#205]
We have 18 that needs information instead of "ADD MOTIVATION HERE" and "ADD HOW TO FIX VIOLATIONS HERE"

**Comment by SeanKilleen** [comment]
@mikkelbu I believe my #206 PR might close this out if we tweak the language to address the motivation sections. I welcome your feedback there to extract the motivation from my examples. Once I understand the purpose of the motivation section better, I think we might be able to close this issue out.

**Comment by mikkelbu** [comment]
Most of the motivations - at least for the diagnostics that are marked as errors - is that the code would fail at runtime or mark the test as not runnable (depending on how you run the test). I'll review the PR now and make some comments. But I'm already thankful for the contribution 👍 .
