### ISSUE TITLE
Use nullable reference types

### ISSUE THREAD

**Issue by Dreamescaper** [nunit/nunit.analyzers#222]
While we have no public API to annotate, using nullable reference types still will make code easier to write (would be clear whether I am required to do null checks), and safer from NullReferenceExceptions.

Since nullable attributes are not available for netstandard1.6, we need to add them. We can use:
- https://github.com/manuelroemer/Nullable - development-only package with nullable attributes
- https://github.com/tunnelvisionlabs/ReferenceAssemblyAnnotator - nullable attributes + black magic to add annotations to reference assemblies

Also, would be great to have nullability warnings from Roslyn, but it requires to updates Roslyn version to 3+. Not sure whether it's a great idea, as it means that VS2017 support is dropped.

**Comment by mikkelbu** [comment]
Thanks @Dreamescaper, I'll take a look at this probably tonight.

I think it is fine to go with https://github.com/manuelroemer/Nullable initially. 

Regarding nullability warnings from Roslyn and still support VS2017 I was wondering if we could use multitargeting and then just use the netcoreapp3.0 target for helping in the development, but still releasing the .netstandard in the nuget package - similar to what is proposed in https://www.meziantou.net/how-to-use-nullable-reference-types-in-dotnet-standard-2-0-and-dotnet-.htm. But I'm unsure if it is doable, as I've only done very little work wrt. .NET Core 3.0 (and looking back this seems similar to your concerns in https://github.com/nunit/nunit.analyzers/issues/157#issuecomment-549176550).

**Comment by Dreamescaper** [comment]
By Roslyn warnings I meant having nullable annotations in CodeAnalysis classes.
We don't need netcoreapp3 for that.

We need to update to netstandard2.0 (which is probably not a great deal) and to update CodeAnalysis package to 3+ version (which have dropping VS2017 support).

**Comment by mikkelbu** [comment]
Ok. My understanding was that to get nullable annotations in any MS project then one needed to be netcoreapp3/netstandard2.1. I was just wondering if we in multi-targeting could refer to different versions of CodeAnalysis from the two targets and then keep the code as shared as possible, just so we don't need to have too much duplication if we decide to go for an analyzer for 2017 and one for 2019.

But I think this is a good - and necessary - first step.

**Comment by Dreamescaper** [comment]
As far as I know, analyzers do not support netstandard2.1 anyway, so multi-targeting won't help here.
Probably that's possible using some compiler constant though.

**Comment by jnm2** [comment]
> As far as I know, analyzers do not support netstandard2.1 anyway, so multi-targeting won't help here.
Probably that's possible using some compiler constant though.

Analyzers built for netstandard2.1 will work fine with `dotnet` tooling with SDK 2.1 and newer, but they will not work with VS which runs analyzers in-process on .NET Framework. It is possible to multitarget, e.g. `net472;netcoreapp3.1`, but it requires a .targets file to create the correct `<Analyzer>` project item depending on whether you're in VS or running on .NET Core.

**Comment by Dreamescaper** [comment]
@jnm2 
Yeah, but I'm not sure if there's any point in multi-targeting at all. We can use `netstandard2.0` for both VS2017 and VS2019.

**Comment by Dreamescaper** [comment]
@jnm2 
Btw, do you have any concerns against using ReferenceAssemblyAnnotator? 
Curious, because I remember you suggested using it for https://github.com/nunit/nunit, but ended up adding required nullable attributes manually.

**Comment by jnm2** [comment]
The only reason I didn't use it in NUnit is because ReSharper acts up and can't find any of the reference assemblies when you're targeting .NET 3.5 or lower and using ReferenceAssemblyAnnotator. I haven't been able to get to the bottom of it yet. I haven't noticed any issues using RAA with ReSharper on .NET Framework 4.6+ or .NET Standard/Core.

**Comment by jnm2** [comment]
> Yeah, but I'm not sure if there's any point in multi-targeting at all.

Either using RAA or adding a netcoreapp3.0+ target will cause the BCL to be annotated. Multitargeting is not as preferable as RAA because you'll still get unnecessary warnings on all targets besides netcoreapp3.0+ due to their copy of the BCL not being annotated.
