### ISSUE TITLE
NUnit2023 fires on variables of type Task

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit.analyzers#258]
The following code results in an 'The type of the actual argument - 'void' - can never be null.

```
Task task = Task.Run(Do.Nothing);
Assert.That(task, Is.Not.Null);
```

The source code does an Unwrap of an awaitable type regardless if it is actually awaited:
```
            if (actualType.IsAwaitable(out var awaitReturnType))
                actualType = awaitReturnType;
```

Roslyn should already do that for us when called like:
```
                Task task = Task.Run(Do.Nothing);
                Assert.That(await task, Is.Not.Null);
```

**Comment by manfred-brands** [comment]
Related to this:
Raising NUnit2020 when comparing task for Reference:
```
Task task = Task.Run(Do.Nothing);
Task same = task;
Assert.That(same, Is.SameAs(task));
```
Raising NUnit2021 when comparing tasks for Equals:
```
Task task = Task.Run(Do.Nothing);
Task same = task;
Assert.That(same, Is.EqualTo(task));
```

**Comment by Dreamescaper** [comment]
> The source code does an Unwrap of an awaitable type regardless if it is actually awaited.

Yes, because NUnit waits for tasks in asserts, you don't have to await it explicitly, i.e. this one is perfectly valid:
```
var task = Task.FromResult(3);
Assert.That(task, Is.EqualTo(3));
```

Still, probably non-generic Task case was missed here.

**Comment by manfred-brands** [comment]
Are you sure about NUnit implicitly waiting?

Your example fails on my machine:

>  Expected: 3
      But was:  <System.Threading.Tasks.Task`1[System.Int32]>

I fixed my original problem by changing the code in AssertHelper.UnwrapActualType to:

```
            if (actualType.IsAwaitable(out var awaitReturnType) && awaitReturnType.SpecialType != SpecialType.System_Void)
                actualType = awaitReturnType;
```

Are you happy for me to raise a PR for that?

**Comment by Dreamescaper** [comment]
No, you're right.

I mix it up with `ActualValueDelegate` overload, so this is correct in NUnit:
`Assert.That(() => Task.FromResult(3), Is.EqualTo(3));`

I suppose that Task handling should be reworked to account for them better.
