### ISSUE TITLE
Get inspiration from the performance improvements made for the xunit.analyzers

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#270]
See https://github.com/dotnet/roslyn/pull/46349 which refer to 
* xunit/xunit.analyzers#142 - Move syntax checks before semantic checks
* xunit/xunit.analyzers#143 - Convert SyntaxNode analyzers to symbol analyzers
* xunit/xunit.analyzers#145 - Rewrite AssertUsageAnalyzerBase as an IOperation analyzer

**Comment by Dreamescaper** [comment]
I'd suggest to add some benchmarks beforehand to be able to track the differences.

**Comment by Dreamescaper** [comment]
> Rewrite AssertUsageAnalyzerBase as an IOperation analyzer

I'll take a look at this part.

**Comment by Dreamescaper** [comment]
I'll work on TestCaseUsage and TestCaseSourceUsage analyzers (to migrate either to IOperation, or symbols analyzers).

**Comment by mikkelbu** [comment]
Closed by #282 and #285
