### ISSUE TITLE
NUnit2003: Add code fix with less explicit overload for testing if something is true

### ISSUE THREAD

**Issue by chm-tm** [nunit/nunit.analyzers#273]
Consider changing
> Consider using Assert.That(expr, Is.True) instead of Assert.IsTrue(expr).

to

> Consider using Assert.That(expr) instead of Assert.IsTrue(expr).

I prefer less words if possible, and consider the shorter overload perfectly readable.

Perhaps it's possible to provide two code fixes for everyone's taste.

Thanks for that great tool, guys!

**Comment by manfred-brands** [comment]
It would result in inconsistent code compared to checking for false which cannot be shortened without changing 'expr'.

**Comment by chm-tm** [comment]
Isn't this just a matter of taste as I already stated above, @manfred-brands? _Inconsistent_, of course, sounds bad. I'd call it asymmetric at worst. It's as asymmetric as it'd be in a simple `if` statement: `expr` vs `!expr`.

I've changed the title in order to not force a judgement of the two approaches.

**Comment by manfred-brands** [comment]
I implemented this for you:
![image](https://user-images.githubusercontent.com/8655218/89550891-cdc37e80-d83c-11ea-8e17-fbe2621ad1ee.png)
