### ISSUE TITLE
NUnit2021 fires on delegates

### ISSUE THREAD

**Issue by chm-tm** [nunit/nunit.analyzers#274]
```C#
Action x = () => { };
var y = x;
Assert.That(y, Is.EqualTo(x));
```
The test actually succeeds.
NUnit2021 isn't expected to fire on `x`.

**Comment by manfred-brands** [comment]
This is related to #258 It goes wrong in the same method. It tries to get the return type of the delegate which is void.

My changes don't break any of the existing unit test and solve the new test I added for your use case.

I just raised a PR for the fix.
