### ISSUE TITLE
Consider overload resolution when transforming to comparison constraints

### ISSUE THREAD

**Issue by chm-tm** [nunit/nunit.analyzers#280]
Consider the struct `MyFloat`:

```C#
struct MyFloat
{
    readonly float _value;

    public MyFloat(float value) => _value = value;

    public static implicit operator float(MyFloat value) => value._value;
    public static implicit operator MyFloat(float value) => new MyFloat(value);
}
```
Now consider the following test code:
```C#
float x = 1;
MyFloat y = 2;
Assert.Less(x, y);
Assert.That(x, Is.LessThan(y)); // code fix of NUnit2029 for above statement
```
The first Assert succeeds, but the second Assert fails with the following message:
> System.ArgumentException : Object must be of type Single.

While this is a good indication for `MyFloat` to add some functionality, like to implement `IComparable`, the second Assert is semantically different to the first one.

The expected transform is this one:
```C#
Assert.That(x, Is.LessThan((float)y));
```
That is, the code fixes need to take the classic model overload into account.

**Comment by manfred-brands** [comment]
On the other hand you could say that the Is.LessThan and Is.EqualTo, etc. could utilise the implicit cast.
There is a ticket https://github.com/nunit/nunit/issues/2891 for types that implement IConvertible but it was closed without a fix.

But a code fix should not cause tests to fail.
I will see if the conversion can find out the actual overload of the classic method to account for implicit cast and turning it into an explicit one.

**Comment by chm-tm** [comment]
I imagine this could be quite a big amount of work to get this right everywhere. It could also be rendered superfluous if the framework implementation changes at a later time.
An alternative approach would be to add a note about possible semantic differences to the _How to fix violations_ section of each of the respective analyzers.

**Comment by manfred-brands** [comment]
If you use `Assert.That(x, Is.EqualTo(y));` then NUnit2021 fires complaining the types are not compatible. I'm actually working on #279 which would then cause this to fire for Is.Less etc as well.

**Comment by manfred-brands** [comment]
OK, I managed to create a generic solution.
