### ISSUE TITLE
ClassicModelAssertUsageAnalyser throws InvalidOperationException

### ISSUE THREAD

**Issue by ChrisMaddock** [nunit/nunit.analyzers#3]
I haven't looked in to this too much, but I believe it may be when it encounters a property in the TestFixture class. 

```
Error	AD0001	Analyzer 'NUnit.Analyzers.ClassicModelAssertUsage.ClassicModelAssertUsageAnalyzer' threw an exception of type 'System.InvalidOperationException' with message 'Sequence contains no elements'.	XXX		1	Active	Analyzer 'NUnit.Analyzers.ClassicModelAssertUsage.ClassicModelAssertUsageAnalyzer' threw the following exception:
'Exception occurred with following context:
Compilation: XXX
SyntaxTree: XXX
SyntaxNode: XXX[InvocationExpressionSyntax]@[6922..6945) (162,25)-(162,48)

System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at NUnit.Analyzers.ClassicModelAssertUsage.ClassicModelAssertUsageAnalyzer.AnalyzeInvocation(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__DisplayClass42_1`1.<ExecuteSyntaxNodeAction>b__1()
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock(DiagnosticAnalyzer analyzer, Action analyze, Nullable`1 info)
-----
'.
```

**Comment by JasonBock** [comment]
@ChrisMaddock if possible, please post a code snippet that generates the error, that'll help a lot in trying to figure out where the problem is.

**Comment by ChrisMaddock** [comment]
Sure, sorry, that was a rubbish bug report! 😄 I'll try and write something to replicate it that I can share soon.

**Comment by OsirisTerje** [comment]
JFYI:  I tried to debug with the VSIX; but there everything worked.  For me this error happens with the nuget package, not the vsix.

**Comment by JasonBock** [comment]
@OsirisTerje That's....odd. There shouldn't be a difference between a VSIX installation and NuGet packaging, but....who knows. What does the code look like that causes the exception?

**Comment by OsirisTerje** [comment]
Just standard Assert.AreEqual(4,4);  And the message as shown earlier:  https://cloud.githubusercontent.com/assets/203432/20644138/d9f466cc-b42a-11e6-9ba3-75a6c405f483.png

**Comment by OsirisTerje** [comment]
I wonder if it is something with the target framework, but I added a portable class lib, and got the same issue there, so..... not sure....  But it definitively looks like a loading issue, so it finds some NUnit framework that doesnt match its expectations

**Comment by ChrisMaddock** [comment]
Just to highlight - the exception in this issue is a different one to the one your seeing there @OsirisTerje. I get that too - although hadn't posted an issue about that one as it already seemed to be have been raised. 😄 

I see those File.IO and NullReference exceptions all over - the InvalidOperationException was just from a specific class.

**Comment by JasonBock** [comment]
So let's keep issues separate. If there is a different one, please post a new issue.

**Comment by JasonBock** [comment]
@ChrisMaddock, @OsirisTerje meaning, if there's an issue because the analyzer is referencing NUnit.Framework.dll directly and the projects it's being included in gets messed up because of a reference to a different version of NUnit and/or the Nunit assembly can't be found at all, log that as a separate issue and then I'll track that down.

**Comment by OsirisTerje** [comment]
You have two symptoms pointing to probably  the same cause.  Do you need another issue to track that?

**Comment by JasonBock** [comment]
@OsirisTerje I don't know. At this point I can't tell what the exact issue is here.

**Comment by JasonBock** [comment]
Oops, wrong button :)

**Comment by JasonBock** [comment]
I created a project that referenced the NuGet package as well as the NUnit package and the analyzers worked just fine. So....I'm not sure how to get the issues being reported here....

**Comment by JasonBock** [comment]
Aha! I think I can get it to happen locally :). Now....to figure out what the problem really is....

**Comment by JasonBock** [comment]
OK, I **think** I've figured out where that "sequence contains no elements" is coming from. Try it now and see if it fixes it.

The other issue with `FileLoadException` that @OsirisTerje mentioned....I don't know what that is - I haven't had that happen on my machine, whether I use the VSIX or NuGet package. I think it's a separate issue so please log a different issue so I can trace that one down.

**Comment by ChrisMaddock** [comment]
I still see this one - although I'm not sure if there's some sort of cache I should be clearing out?

I'll try and create something reproducible later in the week

**Comment by JasonBock** [comment]
Yeah....I'm wondering if you're really not deploying the latest bits. Not sure....

(Side note, I need to update the version number just so it's obvious that the changes have been deployed)

**Comment by JasonBock** [comment]
@ChrisMaddock it's been a while....have you verified that this bug has been fixed?

**Comment by ChrisMaddock** [comment]
Sorry, my fault.

I tried, but this occurred in a larger test library referencing other tests libraries and it was difficult to pull the analyser in in a clean build, to see it again. I tried to create a minimal example post-fix, but wasn't able to recreate.

I'll close it - if it isn't fixed, then it must be pretty niche, and I can check again once there's a distribution. 😄
