### ISSUE TITLE
Unable to compile test project when classlib with TestCaseSources is referenced

### ISSUE THREAD

**Issue by adamvlasak** [nunit/nunit.analyzers#304]
Hi,

I am trying to use NUnit.Analyzers and also TestCaseSource attribute documented on 

- https://docs.nunit.org/articles/nunit/writing-tests/attributes/testcasesource.html
- https://docs.nunit.org/articles/nunit-analyzers/NUnit1011.html

I have prepared public gist showing the behavior I get while using classlib in test project solution. Maybe I am doing something wrong but I rather tell you about it as it might be scenario not used often.

Steps to reproduce:
- https://gist.github.com/adamvlasak/ff1acb7da54516b8f7a7625b339b88a5

Error I get (even though without NUnit.Analyzers tests run with no problem)
- https://gist.github.com/adamvlasak/ff1acb7da54516b8f7a7625b339b88a5#file-gistfile1-txt-L86

Can you please confirm it is a bug or tell me what I am doing wrong? Thank you very much.

**Comment by Dreamescaper** [comment]
Certainly looks like a bug. 
Will take a look.

**Comment by Dreamescaper** [comment]
@adamvlasak 
I exactly followed your steps, but cannot reproduce this issue.
```
Build succeeded.
    0 Warning(s)
    0 Error(s)
```
Could you share your example project as .zip archive?

**Comment by adamvlasak** [comment]
[foobar.zip](https://github.com/nunit/nunit.analyzers/files/5445050/foobar.zip)

```
PS C:\repos\foobar> dotnet --list-sdks
3.1.202 [C:\Program Files\dotnet\sdk]
3.1.301 [C:\Program Files\dotnet\sdk]
3.1.401 [C:\Program Files\dotnet\sdk]
3.1.403 [C:\Program Files\dotnet\sdk]
```

```
PS C:\repos\foobar> dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.403
 Commit:    9e895200cd

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.403\

Host (useful for support):
  Version: 3.1.9
  Commit:  774fc3d6a9

.NET Core SDKs installed:
  3.1.202 [C:\Program Files\dotnet\sdk]
  3.1.301 [C:\Program Files\dotnet\sdk]
  3.1.401 [C:\Program Files\dotnet\sdk]
  3.1.403 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by Dreamescaper** [comment]
I see. 
We haven't tested for case when data class is located in different assembly.
Interestingly enough this diagnostic does not appear in VS, only during build - probably it is able to resolve source information inside VS.

**Comment by adamvlasak** [comment]
Yeah in VS2019 if you start building the solution you get NUnit1011 errors in both Error List and editor but when you click on one item in Error List it will disappear. That's why it was confusing for me.

**Comment by mikkelbu** [comment]
This should be solved in the next release. A prerelease containing the fix can be found at https://www.myget.org/feed/nunit-analyzers/package/nuget/NUnit.Analyzers/0.6.0-dev-00594 (and newer versions).
