### ISSUE TITLE
NUnit1028 vs. IDisposable

### ISSUE THREAD

**Issue by Numpsy** [nunit/nunit.analyzers#311]
Hi,

If you have a test fixture that implements ```IDisposable```, then the test runner will call ```Dispose()``` after running the tests.

If you have a fixure like that and run the nunit analyzers, you get an NUnit1028 warning on the Dispose() function:

![image](https://user-images.githubusercontent.com/1178570/99111013-3ca23780-25e3-11eb-80d6-b9256da0d97b.png)

I was just wondering if it would be considered reasonable to special case the Dispose() function and not warn about it, given that the test infrastructure does recognize and call it?

**Comment by manfred-brands** [comment]
Yes, I noticed that yesterday myself. Will make a fix shortly.

**Comment by manfred-brands** [comment]
I added the changes for this to an existing PR (#310) for this rule.

In the mean time there is a workaround you can use by declaring the `Dispose` explicit:
```
void IDisposable.Dispose()
{
}
```

**Comment by Numpsy** [comment]
thanks
