### ISSUE TITLE
Analyzer to warn against comparison operators in actual expression

### ISSUE THREAD

**Issue by bretehlert** [nunit/nunit.analyzers#329]
Add an analyzer or set of analyzers to warn against using comparison operators (`==`, `!=`, `>`, `>=`, `<`, `<=`) in the actual expression of `Assert.That`
For example, `Assert.That(value > 0, Is.True)` is bad, it should be `Assert.That(value, Is.GreaterThan(0))`

**Comment by manfred-brands** [comment]
This would be an extension of NUnit2010 (EqualConstraintUsageAnalyzer) which already does this for `==` and `!=`.
Or a new rules based upon that if it gets to messy.
@mikkelbu You can assign this to me.
