### ISSUE TITLE
Analyzer to warn against calling .Length or .Count() in the actual expression

### ISSUE THREAD

**Issue by bretehlert** [nunit/nunit.analyzers#330]
Add an analyzer or set of analyzers to warn against calling `.Count()` or `.Length` in the actual expression of `Assert.That`
For example, `Assert.That(value.Count(), Is.EqualTo(5))` should be `Assert.That(value, Has.Count.EqualTo(5))`

**Comment by mikkelbu** [comment]
Yet another improvement could be to special case the empty collection, so `Assert.That(collection.Count(), Is.EqualTo(0))` becomes `Assert.That(collection, Is.Empty)`.
