### ISSUE TITLE
Add nullable suppression for Assert.Throws

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit.analyzers#333]
`Assert.Throws` is declared to return `Exception?`. It will return `null` if no exception is thrown. This is only relevant when run inside an `Assert.Multiple` call.
To prevent developers having to check for `null` in the trivial cases, add a suppression rule if no `Assert.Multiple` is detected.

**Comment by manfred-brands** [comment]
Create from https://github.com/nunit/nunit/issues/3717

**Comment by mikkelbu** [comment]
Thanks for the report @manfred-brands 👍. I saw the NUnit issue yesterday, but I've been too busy with work and homeschooling the last couple of weeks.
