### ISSUE TITLE
Create a .NETStandard2.0 release

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit.analyzers#336]
We need to be able to release a .netstand2.0 release so that we actually release the `DiagnosticSuppressors`.
Current suggestion is to use 2 versions, with a different major version.

We need to update the build.cake script to run two 'pack' commands.

**Comment by manfred-brands** [comment]
@mikkelbu Have you had any more thoughts on this?

**Comment by mikkelbu** [comment]
@manfred-brands I had planned to do a release around new year with version 2.0 for the original build and 3.0 for the .netstand2.0 build, but the days have been packed with activities. I'll take a look at your PR, and then see if I can make time the coming days for a new release.

**Comment by manfred-brands** [comment]
Thanks @mikkelbu

**Comment by mikkelbu** [comment]
No problem. You did most of the work, I just had to find time to review and publish :)
