### ISSUE TITLE
Nullable suppression for Assert.Throws does not work in presence of a Assert.Multiple block

### ISSUE THREAD

**Issue by smkanadl** [nunit/nunit.analyzers#342]
With regards to https://github.com/nunit/nunit.analyzers/issues/333, I understand that the supression does not work inside an `Assert.Multiple` block. But I would have expect the following scenario to work, which I typically use for such cases.

```
var e = Assert.Throws<Exception>(() => throw new Exception("Test"));
Assert.Multiple(() =>
{
    Assert.That(e.Message, Is.EqualTo("Test'")); // I see a warning here that e might be null
    Assert.That(e.InnerException, Is.Null);
    Assert.That(e.StackTrace, Is.Not.Empty);
});
```

If I remove the `Assert.Multiple` block, the warning is correctly suppressed.

```
var e = Assert.Throws<Exception>(() => throw new Exception("Test"));
Assert.That(e.Message, Is.EqualTo("Test'")); // no warning now
Assert.That(e.InnerException, Is.Null);
Assert.That(e.StackTrace, Is.Not.Empty);
```

Is this some limitation that could be removed?
I am using the 3.0 Version in Visual Studio 2019 Preview 16.9

**Comment by mikkelbu** [comment]
Without looking at the code I think we should be able to determine that the assignment happens outside the `Assert.Multiple`, but I'm unsure how much this will complicate the code.

**Comment by manfred-brands** [comment]
Roslyn raises the 'possible null reference exception' on the line `Assert.That(e.Message, Is.EqualTo("Test'"));`.
The code then determines that this line is inside the `Assert.Multiple` and stops any search for the assignment and hence doesn't suppress. I will see if I can update the code to search for the assignment regardless.
@mikkelbu Please assign the ticket to me.

**Comment by smkanadl** [comment]
@manfred-brands that would be great if it could be improved that way. Thanks for taking care!

**Comment by mikkelbu** [comment]
Thanks @manfred-brands 👍
