### ISSUE TITLE
Warns about passing a non-lambda to Throws assertions.

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit.analyzers#357]
People sometimes write `Assert.That(MyMethod(), Throws.InstanceOf<SomeException>());`  and wonder why it fails.

We need an analyzer rule that detects this and with code-fixes that convert the code to:
`Assert.That(() => MyMethod(), Throws.InstanceOf<SomeException>());`

**Comment by manfred-brands** [comment]
@mikkelbu You can assign this to me.

**Comment by mikkelbu** [comment]
Thanks @manfred-brands
