### ISSUE TITLE
Replace netcoreapp2.1 for test with netcoreapp3.1

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit.analyzers#392]
netcoreapp2.1 is [out of support](https://devblogs.microsoft.com/dotnet/net-core-2-1-will-reach-end-of-support-on-august-21-2021/)

We should update the 'nunit.analyzers.test' project to target netcore3.1 as being the next LTS release.

**Comment by mikkelbu** [comment]
(also this kind of task fits very well with what I can manage at the moment).
