### ISSUE TITLE
Allow using C# 9

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit.analyzers#397]
@mikkelbu Would you be willing to accept a PR to change language version to C#9.
This does not affect runtime as most of it is syntax compiled to the same IL.

However it allows replacing: `!(instance is null)` with `instance is not null` which is far more readable.

We also can remove repeating long generic types with targeted new expression:
```
private static readonly ConcurrentDictionary<Type, CodeFile> cache =
    new ConcurrentDictionary<Type, CodeFile>();
```

Becomes
```
private static readonly ConcurrentDictionary<Type, CodeFile> cache = new();
 ```

**Comment by mikkelbu** [comment]
I don't mind bumping to C# 9 syntax, and I agree with respect to the `is not null` syntax is much more readable (I thought at about this when reviewing #395, but thought that we would solve this in the future).

Regarding "targeted new expression" then I don't mind it for declaration as the one in the example above as the types are close together, so it is easy to see the type we are instantiating (especially when reviewing or in other places without intellisense). I've seen examples such as the following which I don't like, as it makes it harder to determine the type without navigating the code. 
```csharp
	public static string SomeMethod()
	{
		// ... long and complicated method spanning many lines
		return new("Test");
	}
```

**Comment by manfred-brands** [comment]
I have a branch ready, but it is on top of #395 as it fixes those `is not null` cases.
Once that is in master, I will raise this PR.

**Comment by mikkelbu** [comment]
Great. I completely overlooked that you had pushed changes to #395, but the weekend was also packed with activities. I'll try to take a final look at #395 tomorrow.
