### ISSUE TITLE
NUnit2044 false-positive on explicit delegate type

### ISSUE THREAD

**Issue by yaakov-h** [nunit/nunit.analyzers#410]
```csharp
TestDelegate action = resourceStreams.Commit;
Assert.That(action, Throws.InvalidOperationException.With.Message.EqualTo("The unit of work is read-only."));
```

This triggers **NUnit2044**:The type of the actual argument must be a delegate.

In this case, the type already _is_ a delegate, as `resourceStreams.Commit` is a method defined as `public void Commit()`.

**Comment by manfred-brands** [comment]
@yaakov-h You are correct.

It doesn't trigger for me when using:

```
Assert.That(resourceStreams.Commit, Throws.InvalidOperationException.With.Message.EqualTo("The unit of work is read-only."));
```
