### ISSUE TITLE
NUnit2045 raises IndexOutOfRangeException on CodeAnalysis

### ISSUE THREAD

**Issue by ProfBits** [nunit/nunit.analyzers#420]
## Description
NUnit2045 raises IndexOutOfRangeException on executing Analyze -> Run Code Analysis -> On Solution.

Expected: no exception

## How to reproduce

1. Create a new Solution with .net5 ClassLibrary project
2. Add a NUnitTestProject (.net5)
3. Update packges of test project
4. Add NUnit.Analyzers to test project
5. Execute Analyze -> Run Code Analysis -> On Solution

-> An Waring with the IndexOutOfRangeException caused by NUnit2045 will show up in the ErrorList view

## Image:
![grafik](https://user-images.githubusercontent.com/53108880/149086690-c85e405a-8699-44ad-8c0f-e06eb4b69821.png)

## Error message:
```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'NUnit.Analyzers.UseAssertMultiple.UseAssertMultipleAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Der Index war außerhalb des Arraybereichs.'.
Exception occurred with following context:
Compilation: TestProject1
IOperation: Invocation
SyntaxTree: C:\Users\shube\source\repos\NUnitAnalyzerBugExample\TestProject1\UnitTest1.cs
SyntaxNode: Assert.Pass() [InvocationExpressionSyntax]@[222..235) (14,12)-(14,25)

System.IndexOutOfRangeException: Der Index war außerhalb des Arraybereichs.
   bei NUnit.Analyzers.UseAssertMultiple.UseAssertMultipleAnalyzer.AnalyzeAssertInvocation(OperationAnalysisContext context, IInvocationOperation assertOperation)
   bei NUnit.Analyzers.BaseAssertionAnalyzer.AnalyzeInvocation(OperationAnalysisContext context)
   bei Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c.<ExecuteOperationAction>b__63_0(ValueTuple`2 data)
   bei Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: NUnit2045	TestProject1		1	Active
```

## Used Version:

- C# .net5
- VisualStudio Community 2019 16.11.9
- NUnit 3.12.2
- NUnit.Analyzers 3.3.0
- NUnit.3TestAdapter 4.2.0

I do not have a .net6 or VS 2022 instllation at hand, so can't verify for that.

PS Hope thats enough information

**Comment by manfred-brands** [comment]
Thanks for the report.
I haven't managed to reproduce it, but can see when it could happen.

Can you change the `Assert.Pass()` in your project to something like `Assert.Pass("No errors")`?
The code assumes at least one argument.

**Comment by manfred-brands** [comment]
I managed to reproduce the issue in an nunit test and have a fix.

**Comment by ProfBits** [comment]
@manfred-brands Thank you for looking into it so fast, and yes changing it to `Assert.Pass("No errors")` prevents the error from occuring on my system

**Comment by chm-tm** [comment]
@manfred-brands We're suffering from this issue. Do you have a release date for 3.4/2.4?

**Comment by chm-tm** [comment]
Ah I [see I could get the prerelease on myget](https://github.com/nunit/nunit.analyzers/issues/430#issuecomment-1072902405).

**Comment by manfred-brands** [comment]
@chm-tm I do not, but I think one is due. I created #478
