### ISSUE TITLE
Drop the VSIX project

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit.analyzers#429]
The VSIX project only allows the analyzers to run in Visual Studio, which means that CLI build would not use them.

They have been [removed ](https://github.com/dotnet/roslyn-analyzers/issues/3314#issuecomment-747598315) from the VS extension marketplace for the roslyn analyzers.

NuGet package allows different rules/versions for different projects and can be used in CI processes.

**Comment by JohanLarsson** [comment]
A VSIX can still be useful for debugging.

**Comment by manfred-brands** [comment]
I don't seem to be able to even find the nunit.analyzers.vsix on [VS marketplace](https://marketplace.visualstudio.com/search?term=nunit.analyzers&target=VS&category=All%20categories&vsVersion=&sortBy=Relevance)
So I can't check how many downloads there are.

I haven't compiled it for ages. not sure if @mikkelbu uploaded newer versions somewhere.

**Comment by OsirisTerje** [comment]
Debugging using the vsix is not trivial either.  The easiest way to debug is to actually use the code itself, clone the repo and add it to your project.  The next fastest way is to create a local version of the package, in debug mode, and add that package to your project. 

The VSIX project is 5 years old. I don't think it ever was realized. And if it is not present on the marketplace (I can't find it either), it probably never was there.  

Suggest we just remove the remains of the vsix code.

**Comment by mikkelbu** [comment]
I've never uploaded the VSIX anywhere. Prior people used them for debugging - i.e. running the VSIX project from within VS would spin up a new instance of VS with the analyzers and codefixes, but I've personally not used the VSIX in many years. I think it is fine to remove the project.
