### ISSUE TITLE
Using Assert.Ignore() returns exception

### ISSUE THREAD

**Issue by fdfey** [nunit/nunit.analyzers#430]
error AD0001: Analyzer 'NUnit.Analyzers.UseAssertMultiple.UseAssertMultipleAnalyzer' threw an exception of type 'System.IndexOutOfRangeException' with message 'Index was outside the bounds of the array.'

when using:
Assert.Ignore();

changing to:
Assert.Ignore("Ignored");

it fixes

------
Version 3.3.0
.NET SDK 6.0

**Comment by manfred-brands** [comment]
This is similar to #420 and likely fixed by the same PR.
You can try the pre-release package from [myget](https://www.myget.org/feed/nunit-analyzers/package/nuget/NUnit.Analyzers/3.4.0-dev-00868) to confirm.

**Comment by mikkelbu** [comment]
@fdfey I'll try to get a new release out this weekend. Probably tomorrow.

**Comment by manfred-brands** [comment]
Duplicate of #420

**Comment by fdfey** [comment]
> @fdfey We have a minor issue blocking the release, so the release has been delayed until this is resolved.

no worries, I already used the workaround, thanks for let me know! :)
