### ISSUE TITLE
Anaylzer conversion for class with Count property can be incorrect

### ISSUE THREAD

**Issue by b-a-roberts** [nunit/nunit.analyzers#444]
Example code

```csharp
using NUnit.Framework;

namespace Tests
{
    internal sealed class UseHas
    {
        [Test]
        public void UseHasCount()
        {
            MyClass myClass = new();

            myClass.Count = 1;
            Assert.That(myClass.Count, Is.EqualTo(1));
            myClass.Count--;
            Assert.That(myClass.Count, Is.EqualTo(0));
        }

        private sealed class MyClass
        {
            public int Count { get; set; }
        }
    }
}
```
Gets converted to

```csharp
using NUnit.Framework;

namespace Tests
{
    internal sealed class UseHas
    {
        [Test]
        public void UseHasCount()
        {
            MyClass myClass = new();

            myClass.Count = 1;
            Assert.That(myClass, Has.Count.EqualTo(1));
            myClass.Count--;
            Assert.That(myClass, Is.Empty);
        }

        private sealed class MyClass
        {
            public int Count { get; set; }
        }
    }
}
```
Obviously the above then throws at run time, because 'MyClass' is not enumerable. Ideally the analyzer should not suggest changes where the type requires a specific implementation that it does not support.

**Comment by stevenaw** [comment]
Thanks @b-a-roberts 
I'm not able to test your code at the moment, but does it fail at runtime using v3.13.3 of the framework? I recall a fix had to be made there recently to support Count on Priorityqueue, which also doesn't implement IEnumerable

**Comment by manfred-brands** [comment]
The above does indeed fail with 3.13.2 and passes with 3.13.3.

We have a bit of a dilemma: `PriorityQueue` is a "Collection" which does not implement `IEnumerable`, but has a `Count` property. For this `Is.Empty` makes sense. That is the reason for the change in Nunit.Framework.

However not every class with a `Count` property is a collection of something, it could be just counting the number of visitors to a web site.

I'm going to change the code-fix to only generate `Is.Empty` if the type implements IEnumerable.
