### ISSUE TITLE
False positives for NUnit2021 (Incompatible types for EqualTo constraint)

### ISSUE THREAD

**Issue by geoff-m** [nunit/nunit.analyzers#464]
![image](https://user-images.githubusercontent.com/22863275/179375235-e1dd7a58-a677-4439-9721-70a8a553632f.png)
`SquareTools.Parse` returns `Square`, (`enum Square : ushort`). The test passes, as expected, despite NUnit's analysis.

Even though there is only one type in the whole solution named Square, I tried fully qualifying it in the `AreEqual` call and in the return type of `Parse`. When I did this, the analyzer stopped reporting the nonexistent problem, even after I reverted to unqualified names. But at the same time, the analyzer started reporting the problem in a different test:
![image](https://user-images.githubusercontent.com/22863275/179375270-3886f78e-c575-440b-81c6-496eeaef022a.png)
This test also passes.

I tried making a new project to reproduce this and was unable. As I mentioned, the problem didn't even come back in the original place after I made the code exactly how it was when the problem was present. 

I am aware this can be worked around by `#pragma warning disable NUnit2021` or by just ignoring what the analyzer reports. Adding and removing this pragma causes the analyzer errors to disappear and appear. I have been using Rider by the way--maybe a bug should be submitted to them?

Versions:
NUnit 3.13.3
NUnit.Analyzers 3.3.0
NUnit3TestAdapter 4.2.1
C# 10
.NET 6 on Windows

**Comment by mikkelbu** [comment]
Closing this since we have not heard back from the reporter. Please note that we will still get notifications on new messages, so if more information appear we can reopen this issue.
