### ISSUE TITLE
False positive for NUnit2021 with Throws/EqualTo contraint

### ISSUE THREAD

**Issue by killergege** [nunit/nunit.analyzers#465]
The following code reports error NUnit2021 (on `EqualTo(exception)`)

```
var exception = new MyException();
_mockedService.MyMethod().Throws(exception);
Assert.That(() => _sut.Handle(), Throws.InstanceOf<MyException>().And.EqualTo(exception));
```

The test passes but `The EqualTo constraint always fails as the actual and the expected value cannot be equal` is reported.

I didn't find any obvious ways to check that the instance thrown is the one expected (and not just type).
If this is not the right way, I'm interested by an alternate solution.

**Comment by manfred-brands** [comment]
I can confirm this bug and will aim to fix it.

**Comment by mikkelbu** [comment]
> I didn't find any obvious ways to check that the instance thrown is the one expected (and not just type).
> If this is not the right way, I'm interested by an alternate solution.

I don't think this can be done using the `Assert.That(...)` syntax, but you can using Assert.Throws<...>(...)`. So something like

```csharp
var exception = new MyException();
_mockedService.MyMethod().Throws(exception);
var thrownException = Assert.Throws<MyException>(() => _sut.Handle());
Assert.That(thrownException, Is.EqualTo(exception));
```
