### ISSUE TITLE
Examine concurrent execution af analyzers

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#47]
Links for inspiration 
* https://github.com/dotnet/roslyn/issues/6737#issuecomment-206623629 (for links to announcement)
* https://docs.microsoft.com/en-gb/visualstudio/releasenotes/vs2015-update2-vs
* https://github.com/xunit/xunit.analyzers/pull/76 
* https://github.com/DotNetAnalyzers/StyleCopAnalyzers/pull/2102/files

**Comment by jnm2** [comment]
I usually flip this on by default. @JohanLarsson would know better than me, but I think that you're fine so long as you don't use static state or analyzer instance state from inside analysis callbacks without making it thread-safe.
