### ISSUE TITLE
Create 3.4.0 release

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit.analyzers#478]
It has been 8 months since the last release, people are reporting bugs already fixed.

Any change for a release (after #477 is merged)?

**Comment by mikkelbu** [comment]
@manfred-brands I think it makes sense for a release 👍 . I've been too busy over summer and wanted to look at https://github.com/nunit/nunit.analyzers/pull/432#issuecomment-1079887847 before releasing, but so far I have not had time (all time have been spent triaging, answering questions, and reviewing in different repos).

I'll see if I can find some time next week.
