### ISSUE TITLE
Reuse TestCaseAttribute logic for ValuesAttribute

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#52]
We should reuse the logic for testing whether the value of a `TestCaseAttribute` matches the argument of the test method to also have effect for `ValuesAttribute`. The following will currently give an analyzer error on `"a"`.

```csharp
    [TestCase("a")]
    [TestCase(-4.0)]
    [TestCase(-9.0)]
    public void Test1(double d)
    {
...
    }
```
But for the following there are no analyzer errors
```csharp
    [Test]
    public void Test2([Values("a", -4.0, -9.0)] double d)
    {
...
    }
```

**Comment by manfred-brands** [comment]
Could have helped with https://github.com/nunit/nunit/issues/4107

**Comment by andrewimcclement** [comment]
I am currently looking at this, though progress is slow (I haven't done anything with ASTs before).

**Comment by manfred-brands** [comment]
@andrewimcclement Let me know if you have any questions or are stuck.

**Comment by andrewimcclement** [comment]
Current working branch is https://github.com/andrewimcclement/nunit.analyzers/tree/aim/values-usage-analyzer, with relevant code to be found at https://github.com/andrewimcclement/nunit.analyzers/blob/aim/values-usage-analyzer/src/nunit.analyzers/ValuesUsage/ValuesUsageAnalyzer.cs.  Not ready to create a pull request.  Need to extract the type of the parameter as well as the type for each argument to the [Values] attribute, then compare them.  Once I have something that works, I'll add more tests and create a pull request.
