### ISSUE TITLE
Suggestion: Warn when AnyOfConstraint is used with an array/collection as the first parameter

### ISSUE THREAD

**Issue by SeanKilleen** [nunit/nunit.analyzers#533]
Follow-up to a great docs observation on https://github.com/nunit/docs/pull/750.

We may want to warn users who use the `AnyOfConstraint` with an array as the parameter.

Example Gotcha:

```csharp
[Test]
public void CanBeUsedWithParameters()
{
    Assert.That(42, Is.AnyOf(0, -1, 42, 100)); // Passes
}

[Test]
public void CantBeUsedWithAnArray()
{
    var array = new[] { 0, -1, 42, 100 };
    Assert.That(42, Is.AnyOf(array)); // Fails
}

[Test]
public void CantBeUsedWithAList()
{
    var list = new List<int>() { 0, -1, 42, 100 };
    Assert.That(42, Is.AnyOf(list)); // Fails
}
```

**Comment by manfred-brands** [comment]
It doesn't help that the framework doesn't have any NUnit test for AnyOf in the framework.
Rather than warning it doesn't help, I would prefer to make it work.

I did the latter in a few lines of code.

**Comment by manfred-brands** [comment]
Declined in favour of https://github.com/nunit/nunit/issues/4355
