### ISSUE TITLE
Allow the *Source Analyzers to permit `Task<IEnumerable>`

### ISSUE THREAD

**Issue by stevenaw** [nunit/nunit.analyzers#542]
Something I found while adding async test case support in https://github.com/nunit/nunit/pull/4389 is that the analyzers needed to be suppressed inline in the added tests since the analyzers only permit `IEnumerable` and not also `Task<IEnumerable>`.

That PR is still pending, so we may want to wait to update the analyzers until the underlying code change merges first.

**Comment by manfred-brands** [comment]
@stevenaw You only allow methods to return `Task<IEnumerable>`. Was this deliberate?
Neither properties nor fields itself are `async`, but they could return a `Task` although I didn't come up with a practical example that should not have been a method to begin with.

**Comment by stevenaw** [comment]
Good point @manfred-brands . It wasn't really a conscious or deliberate choice to exclude fields or properties. More just that, as you say, it was an implicit assumption on my part that work requiring a `Task` would likely be implemented as a method. Even a field like below would need to be initialized through some backing method:

```csharp
private static readonly Task<IEnumerable> MyField = GetMyTaskAsync();
```

That said, it could easily be made to work for fields or properties too. Would it make it easier on the analyzer side if it were?

**Comment by manfred-brands** [comment]
It had all initially for all, but after checking your PR I added a small condition. Either way is fine. It makes more sense this way, so let us leave it as it is.
