### ISSUE TITLE
Buggy interaction between the `Assert.Multiple` fixer and null reference suppression

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit.analyzers#587]
I have the following code
```csharp
Assert.That(Response.StatusCode, Is.EqualTo(HttpStatusCode.OK)); // assert multiple suggestion here
Assert.That(subfolderResponse, Is.Not.Null);
Assert.That(subfolderResponse.FilePath, Is.EqualTo(Subject.FolderPath));
```

Following through with the suggested fixer, however, results in this:
```csharp
Assert.Multiple(() =>
{
    Assert.That(Response.StatusCode, Is.EqualTo(HttpStatusCode.OK));
    Assert.That(subfolderResponse, Is.Not.Null);
});
Assert.That(subfolderResponse.FilePath, Is.EqualTo(Subject.FolderPath)); // warning: dereference of a possibly null value
```

Is there any way that the null reference suppression could be made aware of previous not-null assertions when they're within `Assert.Multiple` calls?

If this is not possible, could the `Assert.Multiple` fixer be disabled in this scenario?

**Comment by manfred-brands** [comment]
Thanks @RenderMichael for reporting this.

**Comment by smkanadl** [comment]
@manfred-brands I recently discovered that the interaction is still buggy.

```

        [Test]
        public void Test()
        {
            string? value1 = null;
            string? value2 = null;

            // These asserts suppress the nullable warnings in the Assert.That()
            Assert.That(value1, Is.Not.Null);
            Assert.That(value2, Is.Not.Null);

            Assert.Multiple(() =>
            {
                // These asserts do not suppress the nullable warnings in the Assert.That()
                Assert.That(value1, Is.Not.Null);
                Assert.That(value2, Is.Not.Null);
            });

            Assert.Multiple(() =>
            {
                Assert.That(value1.Trim(), Is.EqualTo(""));
                Assert.That(value2.Trim(), Is.EqualTo(""));
            });
        }
```

I have recently tested 3.8 and 3.9 and both struggle to suppress the nullable warnings if the `Is.Not.Null` is placed into an `Assert.Multiple` itself. This is quite unfortunate as the analyzer itself suggests to group the `Is.Not.Null` asserts into a `Multiple` lambda.

**Comment by manfred-brands** [comment]
@smkanadl I cannot reproduce your problem, the `Is.Not.Null` is detected:

Without `Is.Not.Null`:

![image](https://github.com/nunit/nunit.analyzers/assets/8655218/5e6442c0-1db3-424f-8a27-86cb8adb2d19)

With `Is.Not.Null`:
![image](https://github.com/nunit/nunit.analyzers/assets/8655218/1b5fe3c5-22fc-4a16-84c8-c7240ba45204)

Note that you need to restart Visual Studio, if upgrading any analyzers.

**Comment by smkanadl** [comment]
@manfred-brands Thanks for confirming that it should be fixed. I re-checked my solution and have to apology.
There project where I tested had a "hidden" reference forcing the analyzer package to resolve to 3.6.1 in all cases I tested.

Sorry for causing confusion! I'll do better next time!

**Comment by manfred-brands** [comment]
@smkanadl No problem.
