### ISSUE TITLE
Release 3.7.0 notes not correct

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit.analyzers#592]
Hi @mikkelbu 

Thanks for creating the release.

It seems that #588 is not in the release.
Not sure how you created the binaries.
We either need to create 3.7.1 or update the release notes.

**Comment by mikkelbu** [comment]
Hi @manfred-brands 

I think #588 is part of the release, but when I create the release notes (a manual process at the moment) I only mention a PR, if there is not an associated issue. So for the current release then #587 is in the release notes and that covers #588. This "template" was initially inherited from the NUnit framework project.

The release process is a little annoying (and manual) at the moment, but so far I've lived with it. But if you have suggestions/opinions of whether the release notes should mention both issues and PRs then I'm open for input.

Ps. The binaries are the ones created by the appveyor build (from the tag 3.7) - so the artifacts of this build https://ci.appveyor.com/project/mikkelbu/nunit-analyzers/builds/48052351

**Comment by manfred-brands** [comment]
Hi @mikkelbu I did somehow get an old nuget package. 
I used nuget package explorer to download the official one and it was correct.
I then deleted all 3.7.0 copies in my nuget package cache and my local (folder) nuget feed.
The code compiles without errors again.

Sorry for the confusion.

**Comment by mikkelbu** [comment]
No problem @manfred-brands. I actually think it could be my "fault" as I've not prioritised #508 yet. At least I'm guessing this is the reason for why I often need to clear all build output (also temp) and vs caches when changing versions of this package.
