### ISSUE TITLE
3.7.0 breaks build when using TestCase(null) in a method that expects a string

### ISSUE THREAD

**Issue by LauraXiulan** [nunit/nunit.analyzers#593]
We have a test in our code that checks whether a string can be parsed to an int. That used to work up until the newest 3.7.0 version. Now the build breaks on: 
"error NUnit1001: The value of the argument at position '0' of type <null> cannot be assigned to the parameter 'str' of type string".

To reproduce:

   ```
 [TestCase(null)]
 public void Int32(string str) => IsInt(str).Should().BeFalse();

 public static bool IsInt(string? value) => int.TryParse(value, out int _);
```

**Comment by manfred-brands** [comment]
I see you use nullable reference types, this mean you need to change your test to accept `string?` instead.

**Comment by manfred-brands** [comment]
Your code:
![image](https://github.com/nunit/nunit.analyzers/assets/8655218/3e123439-81b7-42a2-93e8-744edbf65bb0)

Fixed code:
![image](https://github.com/nunit/nunit.analyzers/assets/8655218/4dbcb879-30df-42be-9b3e-5ff6c0fba95a)
