### ISSUE TITLE
NUnit1032 for not IDisposable property

### ISSUE THREAD

**Issue by Dmalkov1993** [nunit/nunit.analyzers#594]
Hello!

We use the IServiceProvider property in our tests.
After updating NUnit.Analyzers to version 3.7.0, we began to receive the error ": The property should be Disposed in a method annotated with OneTimeTearDown"

I haven't found a way to suppress this error.
Tell me how to deal with this error?

```csharp
[SetUpFixture]
public class TestsInitializer
{
    public static IServiceProvider Provider { get; private set; }

    [OneTimeSetUp]
    public void Initialize()
    {
        var services = new ServiceCollection();

        // Creation mocks and dbContext

	// Add mocks to DI
       
	// Initialize IServiceProvider
        Provider = services.BuildServiceProvider();
    }

    [OneTimeTearDown]
    public async Task DropDatabases()
    {
        var dbContext = Provider.GetRequiredService<DbContext>();
        await dbContext.Database.EnsureDeletedAsync();
		
        // Problem: IServiceProvider (property Provider) not Disposable
    }
}
```

**Comment by manfred-brands** [comment]
@Dmalkov1993 The `Dispose` is needed to release any instances created by the DI.

The return value of [BuildServiceProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollectioncontainerbuilderextensions.buildserviceprovider?view=dotnet-plat-ext-7.0#microsoft-extensions-dependencyinjection-servicecollectioncontainerbuilderextensions-buildserviceprovider(microsoft-extensions-dependencyinjection-iservicecollection)) is a [ServiceProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovider?view=dotnet-plat-ext-7.0) which is `IDisposable`.

If you change the type of `Provider` to `ServiceProvider` you can call `Provider.Dispose()`.
If you don't want to change the type of your property, you can either use a field and property combination
```chsarp
private static ServiceProvider provider;
public static IServiceProvider Provider => provider;
```
Or you can use the following in the `OneTimeTearDown`:
```csharp
if (Provider is IDisposable disposable)
    disposable.Dispose();
```

**Comment by Dmalkov1993** [comment]
> @Dmalkov1993Это `Dispose`необходимо для выпуска любых экземпляров, созданных DI.
> 
> Возвращаемое значение [BuildServiceProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.servicecollectioncontainerbuilderextensions.buildserviceprovider?view=dotnet-plat-ext-7.0#microsoft-extensions-dependencyinjection-servicecollectioncontainerbuilderextensions-buildserviceprovider(microsoft-extensions-dependencyinjection-iservicecollection)) — это [ServiceProvider](https://learn.microsoft.com/en-us/dotnet/api/microsoft.extensions.dependencyinjection.serviceprovider?view=dotnet-plat-ext-7.0) , который имеет формат `IDisposable`.
> 
> Если вы измените тип на `Provider`, `ServiceProvider`вы можете позвонить `Provider.Dispose()`. Если вы не хотите менять тип своего свойства, вы можете использовать комбинацию поля и свойства.
> 
> ```
> private static ServiceProvider provider;
> public static IServiceProvider Provider => provider;
> ```
> 
> Или вы можете использовать следующее в `OneTimeTearDown`:
> 
> ```cs
> if (Provider is IDisposable disposable)
>     disposable.Dispose();
> ```

Thanks! Its works!
