### ISSUE TITLE
Bug: StackOverflowException when test calls recursive method in 3.7.

### ISSUE THREAD

**Issue by andrewimcclement** [nunit/nunit.analyzers#602]
Using .NET Framework 4.8.
This builds fine using NUnit.Analyzers 3.5.0 but fails in 3.7.0 (and 3.8.0):
```csharp
using System;
using System.Collections.Generic;

using NUnit.Framework;

namespace Namespace
{
    internal class Fixture
    {
        private Dictionary<string, bool> _values = new Dictionary<string, bool>();

        [Test]
        public void MinimalRepro()
        {
            Recurse("help");
        }

        private void Recurse(string one, bool keepGoing=true)
        {
            _values[one] = keepGoing;
            if (keepGoing)
            {
                Recurse(one, false);
            }
        }
    }
}
```
Error looks like
![image](https://github.com/nunit/nunit.analyzers/assets/33556313/e91c4c12-f823-42a0-b0f2-107006125e67)
I don't have time to actually debug the analyser right now but I hope this repro is small enough to make it easy.

**Comment by manfred-brands** [comment]
@andrewimcclement Thanks for reporting.

I think I know where the issue is, I just didn't think of recursion when implementing this.

**Comment by manfred-brands** [comment]
@andrewimcclement There are a few possible workarounds for you:

1. Disable NUnit1032 in the class with the recursive method(s) using: #pragma warning disable NUnit1032
2. Disable NUnit1032 for the whole project using: dotnet_diagnostic.NUnit1032.severity = none
3. Move the recursive method to a local function or nested class as the analyzer only checks methods in the same class.
4. Use the NuGet package created from the PR build [artifacts](https://ci.appveyor.com/api/buildjobs/cgvc81cj2blcsyot/artifacts/package%2FRelease%2Fnetstandard2.0%2FNUnit.Analyzers.3.9.0-ci-01285-pr-604.nupkg)

**Comment by andrewimcclement** [comment]
Thanks for the workarounds.  I think I'll probably go with number 2 until a new version is out with the fix, as if it appears elsewhere, it is non-obvious what the fix is for other people in my team.  Many thanks for the speedy investigation.
