### ISSUE TITLE
Support for NUnit 4 legacy asserts

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit.analyzers#606]
In NUnit 4 the classic `Assert` statements will be changed to `ClassicAssert`, and will be in the namespace `NUnit.Framework.Legacy`.

The rules that allow converting the classic asserts to the constraint model should include the `ClassicAssert` class.

Examples of using the classic asserts in NUnit 4 can be found here:  https://github.com/nunit/nunit-csharp-samples

**Comment by OsirisTerje** [comment]
@manfred-brands @mikkelbu We should get this one out before NUnit 4 non-beta is released :-)

**Comment by manfred-brands** [comment]
Yes, I know. We need to make a group of all items that need addressing before release 4.0.
I will create a new _parent_ issue.
