### ISSUE TITLE
Items that need addressing before NUnit 4.0 is released

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit.analyzers#608]
This ticket list a number of issue that we need to do before NUnit4.0 and NUnit.Analyzers 4.0 are released.

* #610 Ensure Test Code works with NUnit4
* #606 Support for NUnit 4 legacy asserts
* #562 Warn use of params for assertion messages
* #609 Drop support for VS before 2019
* #615 Add support for Assert.MultipleAsync
* #617 Update .Within makes no sense rule
* #618 Make Classic Conversion rule for StringAssert 
* #619 Change default severity of Classic Conversion Analyzers
*  #620 Make Classic Conversion rule for CollectionAssert

**Comment by mikkelbu** [comment]
All items have been resolved. So closing this.
