### ISSUE TITLE
Drop support for VS before 2019

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit.analyzers#609]
We currently have separate releases 2.x and 3.x, where the first is the code without the `DiagnosticSuppressors`.
Those were introduced in [roslyn version 3.3.1](https://learn.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.diagnostics.diagnosticsuppressor?view=roslyn-dotnet-3.3.1)
which matches [Visual Studio 2019 16.3](https://learn.microsoft.com/en-us/visualstudio/extensibility/roslyn-version-support?view=vs-2019) which is 4 years old and [predates .NET Core 3.1](https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs).

I expect all users, even those addressing .NET Framework to use later SDKs to take advantage of new C# language feates.

**Comment by manfred-brands** [comment]
@mikkelbu If you agree, could you take this on please?

**Comment by mikkelbu** [comment]
I agree that we should stop the 2.x releases. Looking at https://www.nuget.org/packages/NUnit.Analyzers the 2.x download numbers are a tiny fraction of the 3.x. I'm very busy at the moment, but I think I've time for this (it should be a small task).

**Comment by manfred-brands** [comment]
Depends on #638 which adds more #if NETSTANDARD code.

**Comment by manfred-brands** [comment]
At the same time I wanted to move to .NET8.0 SDK to match NUnit.
However, the corresponding updated Roslyn Analyzer now insists on separating the CodeFix from the Analyzers.
CodeFixes should only be loaded by IDE, not by the build process.

**Comment by manfred-brands** [comment]
In addition to that, unit test fail due some other changes they made: https://github.com/GuOrg/Gu.Roslyn.Asserts/issues/320

**Comment by mikkelbu** [comment]
@manfred-brands I think I'll make an attempt on dropping support for VS 2017 (and lower) for the release this weekend, and then make the release version 4, and then we can push .NET8.0 SDK and bumping Roslyn Analyzers to a future fix.
