### ISSUE TITLE
Change default severity of Classic Conversion Analyzers

### ISSUE THREAD

**Issue by manfred-brands** [nunit/nunit.analyzers#619]
As the Classic asserts have been moved to a legacy package, should we change the severity to error as they won't work with NUnit4.

**Comment by manfred-brands** [comment]
We also might want to change the text from "consider using the constraint model" to something like "NUnit4 only support the constraint model"

**Comment by OsirisTerje** [comment]
We have not moved it to a separate package, but to a separate project.  It is still delivered as part of the NUnit package.

**Comment by manfred-brands** [comment]
Semantics. 

The fact is that if people don't "consider" this, their code will not compile with NUnit4.
We asked them to "consider" this way before I joined the project, the first `ClassicModelAssertUsageAnalyzer` is 7 years old.

We made the decision to move the classic assert to a separate project (in future a separate nuget package) and we had to change the type name and namespace for compilation reasons.

**Comment by OsirisTerje** [comment]
> Semantics
Why do you nag me?

It is not semantics to tell a user "NUnit 4 doesn't support it".  It does support it, just in another namespace.  Imho, I think it would be better to tell the user that.  That would help the user move on in their own pace.

**Comment by manfred-brands** [comment]
> Why do you nag me?

Not intentionally. 

This Analyzer/CodeFix is for converting classic to constraint, not for classic to legacy.
The latter we cannot do as it would result into non-compilable code if used in NUnit3 and if compiled against NUnit4, the code would already not compile and the Analyzer would not even be triggered.

This leaves the latter to become part of the upgrade documentation.

And we will leave the exiting rule as it is.
