### ISSUE TITLE
Add an Analyzer to Verify ParallelScope Usage

### ISSUE THREAD

**Issue by JasonBock** [nunit/nunit.analyzers#64]
According to [this doc](https://github.com/nunit/docs/wiki/Parallelizable-Attribute), values of `ParallelScope` are only valid based on what member the `Parallelizable` is being used on. For example, `ParalleScope.Children` cannot be used on methods. Writing an analyzer to inform the developer of improper value usage would be a nice thing to have.

Edit by mikkelbu: Corrected link.

**Comment by mikkelbu** [comment]
See [the documentation](https://github.com/nunit/docs/wiki/Parallelizable-Attribute) for more information.
