### ISSUE TITLE
LoadException on 3.10-beta

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit.analyzers#649]
Get this one after updating to the beta version:

![image](https://github.com/nunit/nunit.analyzers/assets/203432/a6dc9da3-c1f7-4ef2-b165-80d2290ae0ea)

**Comment by manfred-brands** [comment]
Did you restart Visual Studio when upgrading the analyzer?

**Comment by OsirisTerje** [comment]
That fixed it :-)
