### ISSUE TITLE
NUnit 3 analyzer does not seem to work with Rider

### ISSUE THREAD

**Issue by MeCapron** [nunit/nunit.analyzers#652]
Hi there,

sorry if it's not the good spot to place this request.

Here is the versions I'm using : 

Rider : `2023.2` (also tried with `2022.2`)
NUnit : `3.14.0` (also tried with `4.0.0-beta`)
NUnit Analyzers : `3.9.0`

![image](https://github.com/nunit/nunit.analyzers/assets/49562288/0bb69630-266d-4354-b37e-922eb65dc589)

I tried all `NUnit300X` rules and they do not seem to work for an unknown reason. I already tried to clear the caches of Rider as well as cleaning everything possible just in case.

The rules under `NUnit300X` are working fine as you can see on this screenshot : 

![image](https://github.com/nunit/nunit.analyzers/assets/49562288/64eb79d7-006f-4601-a465-c95d205811eb)

However, [NUnit3002](https://docs.nunit.org/articles/nunit-analyzers/NUnit3002.html) is not working : 

![image](https://github.com/nunit/nunit.analyzers/assets/49562288/16bd99cb-183a-4c21-885e-a74e42b6c372)

Nor [NUnit3001](https://docs.nunit.org/articles/nunit-analyzers/NUnit3001.html) : 

![image](https://github.com/nunit/nunit.analyzers/assets/49562288/8e190f2e-ba2b-4c7e-9b37-d0cda6e1d2dd)

Is there something I'm missing or a conflict somewhere?

Thanks you!

**Comment by manfred-brands** [comment]
@MeCapron According to [this issue](https://youtrack.jetbrains.com/issue/RIDER-45021/Support-Roslyn-based-suppressors), Rider does not support DiagnosticsSuppressors.

**Comment by MeCapron** [comment]
@manfred-brands Thanks you!
