### ISSUE TITLE
`NUnit1032` throws an exception in a specific configuration

### ISSUE THREAD

**Issue by RenderMichael** [nunit/nunit.analyzers#659]
The following code fails:

``` csharp
using NUnit.Framework;

using System.Diagnostics.CodeAnalysis;

namespace NUnitRepro;

[TestFixture]
public abstract class Test : IDataProvider
{
    private readonly DataReader DataReader;

    DataReader IDataProvider.DataReader
    {
        [RequiresUnreferencedCode("Reflection-based JSON")]
        get => DataReader;
    }

    [RequiresUnreferencedCode("Reflection-based JSON")]
    protected Test() => DataReader = new DataReader(this);

    [OneTimeSetUp] public void SetListener() => throw new NotImplementedException();
}

public interface IDataProvider
{
    DataReader DataReader
    {
        [RequiresUnreferencedCode("Reflection-based JSON")]
        get;
    }
}

[RequiresUnreferencedCode("Reflection-based JSON")]
public sealed class DataReader
{
    public DataReader(IDataProvider provider) => throw new NotImplementedException();
}
```

This gives the following error:

``` text
error AD0001: Analyzer 'NUnit.Analyzers.DisposeFieldsInTearDown.DisposeFieldsAndPropertiesInTearDownAnalyzer' threw an exception of type 'System.ArgumentException' with message 'An item with the same key has already been added. Key: DataReader'
```

If you remove `abstract`, or the attribute on the getter of the explicit implementation of `IDataProvider.DataReader` on `Test`, or the `[OneTimeSetUp]` attribute, this starts to work.

**Comment by RenderMichael** [comment]
Visual Studio provides more information:
![image](https://github.com/nunit/nunit.analyzers/assets/12619902/ac8959e2-aee6-45cd-9f1d-f5a92d16dcd7)

**Comment by RenderMichael** [comment]
> It would confuse people reading your code to see whether you are using the property or the field.

Since it’s an explicit implementation, you couldn’t use the property without a cast to the interface. That’s the reason I have it this way: It makes the property invisible to inheritors of the class while retaining `DataReader`’s functionality (not included in this minimal repro)

Is it possible to exclude explicit implementations from the analysis? That’s the only way I know of to get members/fields with the same name.

**Comment by manfred-brands** [comment]
> Is it possible to exclude explicit implementations from the analysis? That’s the only way I know of to get members/fields with the same name.

I added a PR to exclude explicit implementations.
