### ISSUE TITLE
NUnit1027 fired when `CancellationToken` and `[CancelAfter]` is given

### ISSUE THREAD

**Issue by gfoidl** [nunit/nunit.analyzers#663]
Repro (basically just the example from the [docs](https://docs.nunit.org/articles/nunit/writing-tests/attributes/cancelafter.html):
```c#
[TestFixture]
public class MyTests
{
    [Test, CancelAfter(2000)]
    public void RunningTestUntilCanceled(CancellationToken token)
    {
        while (!token.IsCancellationRequested)
        {
            /* */
        }
    }
}
```

**Expected behavior**: the analyzer understand the `[CancelAfter]` attribute, so that the value for the argument will be given by the NUnit framework.

**Actual behavior**: the analyzer triggers 
![grafik](https://github.com/nunit/nunit.analyzers/assets/5755834/342f490c-e736-4f84-ad6b-68f4f74ed731)

**Comment by manfred-brands** [comment]
Thanks @gfoidl that was an embarrassing oversight from me to forget about updating the analyzer. I have put it to my TODO list.
