### ISSUE TITLE
NUnit2021 when using Is.EqualTo(bool) and an async expected value

### ISSUE THREAD

**Issue by appel1** [nunit/nunit.analyzers#665]
```csharp
public Task<bool> Something() => Task.FromResult(false);

[Test]
public void MyTest()
{
  Assert.That(Something(), Is.EqualTo(true));
  Assert.That(Something(), Is.Not.EqualTo(false));
}
```

error NUnit2021: The EqualTo constraint always fails as the actual and the expected value cannot be equal (https://github.com/nunit/nunit.analyzers/tree/master/documentation/NUnit2021.md)

If the expected value is a test case parameter a workaround seems to be:
`Assert.That(Something(), expected ? Is.True : Is.False);`

Or simple make the test case async and await the actual value task instead.

**Comment by OsirisTerje** [comment]
Can you explain what you mean is wrong here ?   Afaic see the warning is correct, you cant compare a Task and a bool.

**Comment by appel1** [comment]
Forgot to mention I'm using NUnit 3 which has an overload for Assert.That that takes a task and applies the constraint to the result of the task, not the task itself.

**Comment by manfred-brands** [comment]
Does the warning go away if you pass in the method by dropping the `()` for the invocation and let unit do the invocation. Or use `() => Something()

**Comment by appel1** [comment]
Thanks. I tricked myself with the generic overload.
