### ISSUE TITLE
NUnit1032 although field is disposed at OneTimeTearDown

### ISSUE THREAD

**Issue by Dor-bl** [nunit/nunit.analyzers#666]
I'm just in the middle of the process of migrating to NUnit 4.0.1 so I`m using the analyzer 
For some reason, I keep getting errors for NUnit 1032 although I'm disposing of that field In the OneTimeTearDown
https://github.com/nunit/nunit.analyzers/blob/master/documentation/NUnit1032.md#nunit1032

Code sample:
```
public class AppStringsTest
{
    private AppiumDriver _driver;

    [OneTimeSetUp]
    public void BeforeAll()
    {
        var capabilities = Caps.GetAndroidUIAutomatorCaps(Apps.Get("androidApiDemos"));
        var serverUri = Env.ServerIsRemote() ? AppiumServers.RemoteServerUri : AppiumServers.LocalServiceUri;
        _driver = new AndroidDriver(serverUri, capabilities, Env.ImplicitTimeoutSec);
        _driver.Manage().Timeouts().ImplicitWait = Env.ImplicitTimeoutSec;
    }

    [OneTimeTearDown]
    public void AfterAll()
    {
        _driver?.Quit();

        if (!Env.ServerIsRemote())
        {
            AppiumServers.StopLocalService();
        }
    }
```
You can see that I'm calling `_driver?.Quit();`
Here is what's been exuded on that side: 

```
        //
        // Summary:
        //     Close the Browser and Dispose of WebDriver
        public void Quit()
        {
            Dispose();
        }
```

![image](https://github.com/nunit/nunit.analyzers/assets/59066376/7b12dbad-dfb8-4b4d-87d6-1e26cf1b2c9d)

**Comment by manfred-brands** [comment]
Thanks @Dor-bl for your report.

The analyzer does not know anything about the `Quit` method and it won't drill down in any called method in external code to see if `Dispose` might be called there.

As `Dispose` should be callable safely multiple times you can add `_driver.Dispose();` to remove the warning.

If `Quit` is used in multiple places as a dispose method you can add it as a recognised alternative in your `.editorconfig` file like:
`dotnet_diagnostic.NUnit1032.additional_dispose_methods = Quit`

**Comment by Dor-bl** [comment]
@manfred-brands Thanks for the info, It helped me in most cases.
I still encounter this issue in one other place although I updated my `.editorconfig` as suggested.

![image](https://github.com/nunit/nunit.analyzers/assets/59066376/9d342dec-c219-4c9c-98c8-2b14780e07a6)

```

        private AndroidDriver _driver;
        private const string ClipboardTestString = "Hello Clipboard";
        private const string Base64RegexPattern = @"^[a-zA-Z0-9\+/]*={0,2}$";

        [OneTimeSetUp]
        public void BeforeAll()
        {
            var capabilities = Caps.GetAndroidUIAutomatorCaps(Apps.Get("androidApiDemos"));
            capabilities.AddAdditionalAppiumOption(MobileCapabilityType.FullReset, true);
            var serverUri = Env.ServerIsRemote() ? AppiumServers.RemoteServerUri : AppiumServers.LocalServiceUri;
            _driver = new AndroidDriver(serverUri, capabilities, Env.InitTimeoutSec);
            _driver.Manage().Timeouts().ImplicitWait = Env.ImplicitTimeoutSec;
        }

        [SetUp]
        public void SetUp()
        {
            _driver?.LaunchApp();
        }

        [TearDown]
        public void TearDown()
        {
            _driver?.CloseApp();
            _driver.Quit();
        }
```

`.editorconfig` file:

```
root = true

[lib/**.js]
indent_style = space
indent_size = 4

[*.cs]
indent_style = space
indent_size = 4

# Set up additional disposal methods for a specific diagnostic rule
dotnet_diagnostic.NUnit1032.additional_dispose_methods = Quit
```

**Comment by manfred-brands** [comment]
You are initialising `_driver` in a `OneTimeSetUp` method, therefore you must dispose it in a `OneTimeTearDown` method. Otherwise the driver will be disposed for a 2nd test.

Note that you don't need to use `?.` The analyzer will tell the compiler that the variable was initialised and therefore you can say `_driver.Quit()`
