### ISSUE TITLE
NUnit1001 False Positive

### ISSUE THREAD

**Issue by BrianHamil** [nunit/nunit.analyzers#672]
Using NUnit 4.0.1
NUnit.Analyzers 3.10.0
NUnit3TestAdapter 4.5.0

NUnit1001: designed to throw an error if object types don't match
This throws a fatal error if trying to pass null to a test. 
This was not an issue with previous versions.

Example: [TestCase(1, null, "", "2")]

Current workaround: Suppression of message. Tests run and no error shown.
    
[System.Diagnostics.CodeAnalysis.SuppressMessage("Structure",
    "NUnit1001:The individual arguments provided by a TestCaseAttribute must match the type of the corresponding parameter of the method",
    Justification = "Reason...")]

**Comment by manfred-brands** [comment]
@BrianHamil as this rule compares testcase arguments with the test method parameters can you show me the signature of your test method.

Version 3.10 is nullable aware so if you want to pass in `null` your parameter must be declared to allow so, i.e. have a `?` suffix on its type.

**Comment by BrianHamil** [comment]
I've tried changing to nullable but still get the error

        [TestCase(1, null, 2022, 0)]
        public void GetVacationBids_BadRequest_Test(int InflightWebServiceVersion, string EmployeeId, int year, int slot)

**Comment by BrianHamil** [comment]
Okay, just tried marking nullable again, it actually worked, it just took VS a long time to update the errors.
