### ISSUE TITLE
Global using for Assert to equal ClassicAssert crashes analyzer

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit.analyzers#674]
I added a global "using" alias directive for those who only work with the classic asserts, to make it simpler to continue using them without having to change the code.

![image](https://github.com/nunit/nunit.analyzers/assets/203432/a47db2ed-8606-4a08-9754-81e12a84933c)

This caused the analyzer to crash on two rules as follows:

![image](https://github.com/nunit/nunit.analyzers/assets/203432/c8429cbd-541d-4fa9-a2b3-3dbc1838d509)

The stacktrace is:
![image](https://github.com/nunit/nunit.analyzers/assets/203432/d9d600ae-6648-4475-9b1d-568f809e3f9c)

(Same for both crashes)

Checked on two different computers.

The repro code is added to the NUnit.Issues repo, under a NUnitAnalyzers folder: https://github.com/nunit/nunit.issues/tree/main/NUnitAnalyzer/Issue674

However, loading the solution a second time doesn't trigger the crash, so the crashes may indicate some other background cause, since it reports a "key" is not found.

**Comment by manfred-brands** [comment]
@OsirisTerje I'll have a look.

**Comment by manfred-brands** [comment]
@OsirisTerje I cannot reproduce it.  The term "IsGenericMethod" does not occur in the source code.
Do you have steps to reproduce it, I tried removing/adding the global using line, but I get no exceptions.

**Comment by OsirisTerje** [comment]
Closing this now, as we don't have any repro, me included.
