### ISSUE TITLE
error NUnit1029: The TestCaseSource provides '1' parameter(s), but the Test method expects '1' parameter(s)

### ISSUE THREAD

**Issue by richardissimo** [nunit/nunit.analyzers#685]
Just updated NUnit.Analyzers from 3.10.0 to 4.0.0, and now getting
```
error NUnit1029: The TestCaseSource provides '1' parameter(s), but the Test method expects '1' parameter(s) 
```
Example code:
```
namespace Irrelevant
{
    using NUnit.Framework;

    [TestFixture]
    public class NamespaceTests
    {
        [TestCaseSource(nameof(GetAllProjects))]
        public void Class_namespaces_are_correct(string projectFileName)
        {
            // implementation irrelevant
        }

        private static IEnumerable<string> GetAllProjects()
        {
            // implementation irrelevant
        }
    }
}

```

**EDIT**: apologies, it has become apparent that the following line was relevant to the problem, insert the following before the TestCaseSource line: `[CancelAfter(30000)]`

**Comment by mikkelbu** [comment]
Thanks for the report @richardissimo. I cannot reproduce the problem. Do the problem still appear if you clear VS cache and the `bin`/`obj` folders ?
![image](https://github.com/nunit/nunit.analyzers/assets/1007631/60aed34c-8fdf-4a22-9f42-7832ac7d3d1f)

**Comment by katzenbier** [comment]
I have the same problem. Even after running `git clean -Xdf` and restarting Visual Studio, the error persists.
It also happens on `dotnet build`, so it's not a Visual Studio problem.

**Comment by katzenbier** [comment]
I wasn't able to reproduce it with @richardissimo's code.
It seems to only work if you add a `CancelAfter` to the test.
```cs
using NUnit.Framework;
namespace None;
public class Class1
{
    private static IEnumerable<string> TestSettings => ["1"];
    [CancelAfter(20_000),TestCaseSource(nameof(TestSettings))]
    public static void Test1(string name) { }
}
```

```xml
<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>12.0</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.8.0" />
    <PackageReference Include="NUnit" Version="4.0.1" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="NUnit.Analyzers" Version="4.0.0" />
  </ItemGroup>

</Project>
```

Triggers:
`Class1.cs(6,41): error NUnit1029: The TestCaseSource provides '1' parameter(s), but the Test method expects '1' parameter(s)`

**Comment by richardissimo** [comment]
I apologise, I can confirm my test has a CancelAfterAttribute - I hadn't spotted that was related; but I can confirm that by removing the CancelAfter attribute, the complaint about TestCaseSource attribute goes away, so it is the combination of CancelAfter with TestCaseSource.

**Comment by katzenbier** [comment]
I think it was this one: #678.
`src/nunit.analyzers/TestCaseSourceUsage/TestCaseSourceUsesStringAnalyzer.cs`
The analyzer seems to assume that every method with the `CancelAfterAttribute` must have a `CancellationToken` parameter.
But the diagnostic still only reports 1 parameter (The `1` is hard-coded).

**Comment by manfred-brands** [comment]
It is true that `CancelAfter` only works if the test actually uses and obeys the NUnit `CancellationToken`,  either passed in as a parameter or the member in `TestExecutionContext`. 
Although my preferred way is the extra parameter, the analyzer should see it as optional.
I'll see what I missed.

**Comment by manfred-brands** [comment]
So I can confirm the error:

![image](https://github.com/nunit/nunit.analyzers/assets/8655218/82be074c-f867-4de4-86a5-f007a402b357)

Also that it goes away if you add the `CancellationToken` parameter:

![image](https://github.com/nunit/nunit.analyzers/assets/8655218/37556fed-164b-4c17-bb07-bd41d64f97a1)

**Comment by mikkelbu** [comment]
I'll get a release out as quickly as possible, but I'm busy all day tomorrow, so I guess it will be Thursday.
