### ISSUE TITLE
Unable to load

### ISSUE THREAD

**Issue by OsirisTerje** [nunit/nunit.analyzers#724]
In the adapter I upgraded to latest version of the analyzer, and was rewarded by the warnings below:
![image](https://github.com/nunit/nunit.analyzers/assets/203432/056c9e97-c40e-45b5-a012-f42e473584a8)

The adapter runs both .netcore3.1 and net462.  Is there any issues with one of these targets ?

**Comment by mikkelbu** [comment]
@OsirisTerje Have you tried a `git clean -xdf` after the upgrade to remove all the VS cache files in the file system? Usually, removing all temporary files have solved problems like this.

**Comment by manfred-brands** [comment]
@OsirisTerje You need to restart VS if you upgrade Analyzers. VS gets confused.

If there is still an issue I can have a look at your branch.
The target framework doesn't matter for the analyzer as it is started by csc/msbuild
What is version of the SDK are you using?

**Comment by manfred-brands** [comment]
@OsirisTerje I checked out the adapter code and updated NUnit.Analyzer to 3.8.0. It compiles fine. No issues found. Also no problem in VS. Added "classic" code triggers rules so analyzer loads fine.

**Comment by OsirisTerje** [comment]
@manfred-brands I upgraded to 4.1 in the UpdatePackages branch. 
But @mikkelbu 's tip about git clean seems to have done it,  OR your tip of a restart :-)
