### ISSUE TITLE
No Suggestion For IsAssignableFrom and IsNotAssignableFrom 

### ISSUE THREAD

**Issue by sahin52** [nunit/nunit.analyzers#742]
Hello,

When I use latest NUnit.Analyzers V4.2.0, I don't get any suggestion for  
`Assert.IsNotAssignableFrom<RedirectResult>(a);`  

But when I install NUnit V4.1.0, I am getting error for this line:  
`'Assert' does not contain a definition for 'IsNotAssignableFrom'`

I think that should be fixed

**Comment by mikkelbu** [comment]
The work will be done as part of #790
