### ISSUE TITLE
Suggestion: Analyzer Should Fix TestCaseSource(string) usage to use nameof()

### ISSUE THREAD

**Issue by aolszowka** [nunit/nunit.analyzers#80]
Thank you for this tool.

We have several Test Cases that look similar to this:

```
[TestCaseSource( "_SetupIsNotEqualToNoEntryErrorBehaviorTestCases" )]
```

These were written before the introduction of [nameof()](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/nameof) and if they were to be re-written today would look like this:

```
[TestCaseSource( nameof(_SetupIsNotEqualToNoEntryErrorBehaviorTestCases) )]
```

This way Intellisense would operate correctly (F12/Renaming/Find Usages/etc).

I realize that you would be required to use a compiler/IDE that supports C# 6.0 (that usually means Visual Studio 2015) but it would encourage others to keep current.

Thank you for your consideration.

**Comment by mikkelbu** [comment]
Hi @aolszowka
I think that it is a great improvement (as far as I can remember Resharper already has some similar logic to allow you to navigate from the string to the method). I don't worry about the VS 2015 too much as people can you decide not to enable this functionality if they cannot use it.

**Comment by aolszowka** [comment]
I am going to take a stab at this today.

**Comment by aolszowka** [comment]
I am stalled on the fixer; any chance we could at least get the Analyzer reviewed and merged in? Would be a good starting point for anyone with the skills to write the fix.
