### ISSUE TITLE
Partition the analyzers into categories and create identifier ranges for each category

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#84]
Currently, the analyzer identifiers are just consecutively numbered with no meaning behind a given number. Instead we should create ranges for each area of analyzers and reassign the identifiers - similar to what most other analyzer projects do.

**Tasks:**
* Partition the existing analyzers into groups (and perhaps also take into account the existing open issues)
* Create a range of identifiers for each group and reassign identifiers to the analyzers

**Comment by aolszowka** [comment]
I like the idea of doing like NUAxxxx (NUnit Analayzer)

I really like StyleCop which has given "ranges" to their identifiers: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/DOCUMENTATION.md

Another place for improvement is making our documentation similar to StyleCop's like this: https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1400.md the reason being is it makes it easy to link the documentation for those warnings from within Visual Studio or even CI builds.

Below is an example that I have in our CI system:

![image](https://user-images.githubusercontent.com/2592881/50244381-0b844280-038d-11e9-81ab-afaf7491c10d.png)

I would not mind adding the documentation for the fixes I've already contributed after the new year.

**Comment by Dreamescaper** [comment]
Probably we need to define them first. I can see three groups:
1. Suggestions to update non-supported code. Currently we have only classic asserts here.
2. Tests organization. TestCaseUsage, TestCaseSource usages, #5 , #6 , etc.
3. Assert usage. IgnoreCaseUsage, ConstActualValueUsage, #128 , #39 , etc. I suspect that most analyzers will be here.

Anything else?

**Comment by mikkelbu** [comment]
I thought a little about this issue one week ago, but I did not have time to type in my handwritten notes :). Strongly inspired by xUnit and other Roslyn analyzers I also ended up with three categories with much the same content as you (I've reordered the list to match yours):
* **Best practices**
  - This could be non-supported code, but also to highlight different ways one can improve the test code. This could be to make use of nameof instead of string constants - #82 - proper use of ParallelScope - #64 - etc. 
* **Structure**
  - Structural problems with the code that will make it fail at runtime. Missing TestCaseSources - #92 -, non-public test methods, testcases that don't supply enough or too many items, when ExpectedResult does not match the return type - #75 - ...
* **Assertions**
  - Same as you.

I'm not sure if **Assertions**  or **Structure** will be the largest category as both can have a lot of cases, especially if we are going to cover most of NUnit. Also I've been in doubt whether **Best practices** is actually more or less the same as "warnings" and **Structure** the same as "errors", but there are analyzers for a given area e.g. ParallelScope where some of the diagnostics of the analyzer are warnings and some are errors.

xUnit also have a "technical" category, but I think we should wait with that, as currently I cannot think of of any instances of this in NUnit.

My plan was to do this issue and then release version 0.2 as nuget package, but the last couple of weeks have been busy. Perhaps I'll have time to take a look at it this weekend.

**Comment by Dreamescaper** [comment]
Difference between 'Best practices' and 'Structure' is not really clear. From your description it sounds more like Severity, not area/category.
Maybe merge them, and leave only two categories so far?

**Comment by Dreamescaper** [comment]
@mikkelbu 
I'll submit PR with those changes in order to make discussion easier, unless you've already started working on it.

**Comment by mikkelbu** [comment]
Actually, I've already started it, but the last two weeks have been too busy, so I've not made much progress. I'll see if I can get something ready tonight (in 3-4 hours).

**Comment by mikkelbu** [comment]
Sorry, I got sidetracked by other NUnit tasks, so did not have time to do much about the implementation. The categories should be **NUnitxxxx** where `xxxx` are a four digit number.

# Categories
* **Structure**. Range from 1000 to 1999. Covers problems with tests. This could be:
  * non-supported code
  * highlighting different ways one can improve the tests
  * highlighting problems with the test code that will make it fail at runtime
* **Assertions**. Range from 2000 to 2999. Covers all analyzers related to assertions.

| Identifier | Name                                                         | Category  | severity |
|------------|--------------------------------------------------------------|-----------|----------|
| NUNIT_1    | FalseUsage                                                   | Structure | Warning  |
| NUNIT_2    | IsFalseUsage                                                 | Structure | Warning  |
| NUNIT_3    | IsTrueUsage                                                  | Structure | Warning  |
| NUNIT_4    | TrueUsage                                                    | Structure | Warning  |
| NUNIT_5    | AreEqualUsage                                                | Structure | Warning  |
| NUNIT_6    | AreEqualUsage                                                | Structure | Warning  |
| NUNIT_7    | TestCaseParameterTypeMismatchUsage                           | Structure | Error    |
| NUNIT_8    | TestCaseSourceStringUsage                                    | Structure | Warning  |
| NUNIT_9    | TestCaseNotEnoughArgumentsUsage                              | Structure | Error    |
| NUNIT_10   | TestCaseTooManyArgumentsUsage                                | Structure | Error    |
| NUNIT_11   | TestMethodExpectedResultTypeMismatchUsage                    | Structure | Error    |
| NUNIT_12   | TestMethodSpecifiedExpectedResultForVoidUsage                | Structure | Error    |
| NUNIT_13   | TestMethodNoExpectedResultButNonVoidReturnType               | Structure | Error    |
| NUNIT_14   | ParallelScopeSelfNoEffectOnAssemblyUsage                     | Structure | Warning  |
| NUNIT_15   | ParallelScopeChildrenOnNonParameterizedTestMethodUsage       | Structure | Error    |
| NUNIT_16   | ParallelScopeFixturesOnTestMethodUsage                       | Structure | Error    |
| NUNIT_17   | TestCaseSourceIsMissing                                      | Structure | Error    |
| NUNIT_18   | ConstActualValueUsage                                        | Assertion | Warning  |
| NUNIT_19   | TestMethodAsyncNoExpectedResultAndVoidReturnTypeUsage        | Structure | Error    |
| NUNIT_20   | TestMethodAsyncNoExpectedResultAndNonTaskReturnTypeUsage     | Structure | Error    |
| NUNIT_21   | TestMethodAsyncExpectedResultAndNonGenricTaskReturnTypeUsage | Structure | Error    |
| NUNIT_22   | IgnoreCaseUsage                                              | Assertion | Warning  |
| NUNIT_23   | SameActualExpectedValue                                      | Assertion | Warning  |

Seeing the list above, I'm thinking that you were right in proposing a category for non-supported functionality for the first 6 analyzers.

**Comment by Dreamescaper** [comment]
@mikkelbu 
I thought about those 6 as well recently.
Any reason not to put them to Assertion category?

**Comment by mikkelbu** [comment]
@Dreamescaper No. I've just always considered them different :). But I think it is fine to place them in the assertion category. We can always improve on the categories later on (this will of cause break people that have code/configuration depending on the identifiers, but I'm guessing that very few people has this at this point in time).
