### ISSUE TITLE
Analyzer to ensure that the "target" of TestCaseSourceAttribute exists and is static

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#92]
The target of `TestCaseSourceAttribute` should refer to a static field, property or method.

In a subsequent task we can extend this with more of the requirements from https://github.com/nunit/docs/wiki/TestCaseSource-Attribute

For example
> * It must return an IEnumerable or a type that implements IEnumerable. For fields an array is generally used. For properties and methods, you may return an array or implement your own iterator.
> * The individual items returned by the enumerator must be compatible with the signature of the method on which the attribute appears. See the Test Case Construction section below for details.

**Comment by JohanLarsson** [comment]
This will be only four lines of code + tests if #107 is merged, waiting with it until we have a decision there.

**Comment by mikkelbu** [comment]
Not "if", but "when" 😄.
