### ISSUE TITLE
Document implemented analyzers and fixers

### ISSUE THREAD

**Issue by mikkelbu** [nunit/nunit.analyzers#96]
We can probably get inspiration from the other projects:
* https://dotnetanalyzers.github.io/StyleCopAnalyzers/
* https://xunit.github.io/xunit.analyzers/rules/
* https://github.com/DotNetAnalyzers/ReflectionAnalyzers
* https://github.com/GuOrg/Gu.Analyzers

To begin with we should just keep it simple. Then later we can improve on UI and automation

**Comment by JohanLarsson** [comment]
I use a nasty hack for docs: https://github.com/DotNetAnalyzers/AspNetCoreAnalyzers/blob/master/AspNetCoreAnalyzers.Tests/Documentation/Tests.cs

A couple of tests that check that docs exists and generate stub docs if missing. Not pretty but have found it good enough.

**Comment by mikkelbu** [comment]
Thanks for the link, at least it could be useful in the beginning.

**Comment by JohanLarsson** [comment]
I can PR it if you want it like that.

**Comment by mikkelbu** [comment]
Hi @JohanLarsson 
Do you have time for the PR? Or if you don't have time, can you send me the tests or upload them somewhere (this would also help with subsequent updates to the analyzers).

**Comment by JohanLarsson** [comment]
I'll try to find time this week.

**Comment by mikkelbu** [comment]
Closed by #139
